"""Tests for devcontainer_config.certs (spec Section 4.5; E6-F1-S1-T1).

The `devcontainer_config.certs` import is deferred into function bodies (via
`_import_certs`) instead of done once at module scope, for the same reason
`tests/test_repo.py` and `tests/test_hostprobe.py` document: the TDD RED gate
stashes this unit's own production-source files -- `certs.py` is new, added
by this task -- and re-runs a single named test node. A module-level `from
devcontainer_config.certs import ...` would fail COLLECTION for the whole
file (pytest exit code 2, no test outcome recorded) instead of failing the
one named test for the real reason: the module is missing. `_certs_module_path`
reads the file by path rather than importing it, for the identical reason.

Every certificate this file inspects is generated by the module under test,
into a fresh directory under `tmp_path`, and inspected by shelling out to the
real `openssl x509 -noout -text` (SANs, extended key usage) or `-startdate
-enddate` (lifetimes) -- never by re-reading the arguments this module
passed to its own `openssl` calls, which is what makes the SAN and
`clientAuth`/`serverAuth` assertions genuine parses of generated material
(AC-5.2, AC-TEST-001, AC-TEST-002) rather than a test that could pass even if
the generated certificate were wrong.

`issued_material` is a module-scoped fixture: one CA, one server certificate
and one client certificate, issued once into a `tmp_path_factory` directory
and reused by every read-only assertion below (SANs, key usage, modes,
default lifetimes, the "CA already exists" error, and the no-network and
no-stray-file checks). Tests that need a *different* environment --
`CERT_CLIENT_DAYS` overridden, `openssl` missing, no CA created yet -- build
their own fresh `CertPaths` under a function-scoped `tmp_path` instead of
sharing this fixture, since mutating shared state there would make one
test's outcome depend on another's execution order.
"""

from __future__ import annotations

import ast
import datetime
import importlib
import shutil
import socket
import stat
import subprocess
import uuid
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType

import pytest


def _import_certs() -> ModuleType:
    """Import devcontainer_config.certs from inside a function body.

    See the module docstring for why this is not a module-level import.
    """
    return importlib.import_module("devcontainer_config.certs")


def _certs_module_path() -> Path:
    return (
        Path(__file__).resolve().parents[1]
        / ".claude"
        / "plugins"
        / "devcontainer"
        / "scripts"
        / "devcontainer_config"
        / "certs.py"
    )


def _openssl_text(pem_path: Path) -> str:
    """`openssl x509 -noout -text` over a real generated certificate file."""
    result = subprocess.run(
        ["openssl", "x509", "-noout", "-text", "-in", str(pem_path)],
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout


def _openssl_text_from_pem(pem_text: str, tmp_path: Path, name: str) -> str:
    """`openssl x509 -noout -text` over PEM text that has no file of its own.

    `issue_server`'s return value is never written under the material root
    (spec Section 5.5 has no server-key/server-cert row), so a test that
    wants to parse it writes the PEM text to a throwaway path under its own
    `tmp_path` purely to hand it to `openssl` -- this is a test-only
    convenience, not a persistence path the production module ever takes.
    """
    scratch_path = tmp_path / name
    scratch_path.write_text(pem_text, encoding="ascii")
    return _openssl_text(scratch_path)


def _lifetime_days(pem_path: Path) -> int:
    """`notAfter - notBefore`, in whole days, for a real generated certificate."""
    result = subprocess.run(
        ["openssl", "x509", "-noout", "-startdate", "-enddate", "-in", str(pem_path)],
        capture_output=True,
        text=True,
        check=True,
    )
    dates: dict[str, datetime.datetime] = {}
    for line in result.stdout.splitlines():
        key, _, value = line.partition("=")
        dates[key] = datetime.datetime.strptime(value.strip(), "%b %d %H:%M:%S %Y %Z")
    delta = dates["notAfter"] - dates["notBefore"]
    return delta.days


def _file_mode(path: Path) -> int:
    return stat.S_IMODE(path.stat().st_mode)


@dataclass(frozen=True)
class _IssuedMaterial:
    certs: ModuleType
    paths: object
    server: object


@pytest.fixture(scope="module")
def issued_material(tmp_path_factory: pytest.TempPathFactory) -> _IssuedMaterial:
    """One CA, one server certificate and one client certificate, issued once."""
    certs = _import_certs()
    root = tmp_path_factory.mktemp("certs-root")
    instance = f"test-{uuid.uuid4().hex[:8]}"
    paths = certs.CertPaths(instance=instance, root=root)
    certs.create_ca(paths)
    server = certs.issue_server(paths)
    certs.issue_client(paths)
    return _IssuedMaterial(certs=certs, paths=paths, server=server)


# ---------------------------------------------------------------------------
# AC-TEST-001 / AC-TEST-002: SANs and extended key usage, parsed for real.
# ---------------------------------------------------------------------------


def test_server_certificate_has_required_sans_and_no_others(
    issued_material: _IssuedMaterial, tmp_path: Path
) -> None:
    text = _openssl_text_from_pem(issued_material.server.cert_pem, tmp_path, "server-cert.pem")
    san_line = next(line for line in text.splitlines() if "Subject Alternative Name" in line)
    san_values_line = text.splitlines()[text.splitlines().index(san_line) + 1].strip()
    assert san_values_line == "IP Address:127.0.0.1, DNS:localhost"


@pytest.mark.parametrize(
    "expected_usage,role",
    [("TLS Web Server Authentication", "server"), ("TLS Web Client Authentication", "client")],
)
def test_extended_key_usage_matches_role(
    issued_material: _IssuedMaterial, tmp_path: Path, expected_usage: str, role: str
) -> None:
    if role == "server":
        text = _openssl_text_from_pem(issued_material.server.cert_pem, tmp_path, "server-cert.pem")
    else:
        text = _openssl_text(issued_material.paths.client_cert)
    assert expected_usage in text


# ---------------------------------------------------------------------------
# AC-TEST-003: every file/directory mode, and every default lifetime.
# ---------------------------------------------------------------------------


def test_instance_directory_mode_is_0700(issued_material: _IssuedMaterial) -> None:
    assert _file_mode(issued_material.paths.instance_dir) == 0o700


@pytest.mark.parametrize(
    "path_name,expected_mode",
    [
        ("ca_key", 0o600),
        ("ca_cert", 0o644),
        ("client_key", 0o600),
        ("client_cert", 0o644),
    ],
)
def test_material_file_mode(
    issued_material: _IssuedMaterial, path_name: str, expected_mode: int
) -> None:
    path = getattr(issued_material.paths, path_name)
    assert _file_mode(path) == expected_mode


@pytest.mark.parametrize(
    "path_name,expected_days",
    [("ca_cert", 3650), ("client_cert", 90)],
)
def test_default_lifetime_days(
    issued_material: _IssuedMaterial, path_name: str, expected_days: int
) -> None:
    path = getattr(issued_material.paths, path_name)
    assert _lifetime_days(path) == expected_days


def test_default_server_lifetime_days(issued_material: _IssuedMaterial, tmp_path: Path) -> None:
    scratch_path = tmp_path / "server-cert-for-lifetime.pem"
    scratch_path.write_text(issued_material.server.cert_pem, encoding="ascii")
    assert _lifetime_days(scratch_path) == 365


def test_client_lifetime_follows_cert_client_days_override(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """CERT_CLIENT_DAYS is honored, proving the lifetime is not hardcoded at any call site."""
    certs = _import_certs()
    monkeypatch.setenv("CERT_CLIENT_DAYS", "30")
    instance = f"override-{uuid.uuid4().hex[:8]}"
    paths = certs.CertPaths(instance=instance, root=tmp_path)
    certs.create_ca(paths)
    certs.issue_client(paths)
    assert _lifetime_days(paths.client_cert) == 30


# ---------------------------------------------------------------------------
# AC-FUNC-004: invalid lifetime environment values fail fast.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("raw_value", ["not-a-number", "0", "-5"])
def test_invalid_cert_ca_days_raises(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, raw_value: str
) -> None:
    certs = _import_certs()
    monkeypatch.setenv("CERT_CA_DAYS", raw_value)
    paths = certs.CertPaths(instance=f"bad-days-{uuid.uuid4().hex[:8]}", root=tmp_path)
    with pytest.raises(certs.CertsError, match="CERT_CA_DAYS"):
        certs.create_ca(paths)


# ---------------------------------------------------------------------------
# AC-FUNC-001, AC-TEST-004 error path 3: create_ca never silently overwrites.
# ---------------------------------------------------------------------------


def test_create_ca_twice_raises_naming_existing_path(issued_material: _IssuedMaterial) -> None:
    certs = issued_material.certs
    with pytest.raises(certs.CertsError) as excinfo:
        certs.create_ca(issued_material.paths)
    message = str(excinfo.value)
    assert "already exists" in message
    assert str(issued_material.paths.ca_key) in message


# ---------------------------------------------------------------------------
# AC-TEST-004 error path 1: openssl missing from PATH, nothing created.
# ---------------------------------------------------------------------------


def test_openssl_missing_fails_before_creating_anything(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    certs = _import_certs()
    monkeypatch.setattr(certs.shutil, "which", lambda _name: None)
    paths = certs.CertPaths(instance=f"no-openssl-{uuid.uuid4().hex[:8]}", root=tmp_path)

    with pytest.raises(certs.CertsError, match="openssl"):
        certs.create_ca(paths)

    assert not paths.instance_dir.exists()


# ---------------------------------------------------------------------------
# create_ca / issue_server / issue_client both require an existing CA.
# ---------------------------------------------------------------------------


def test_issue_server_requires_existing_ca(tmp_path: Path) -> None:
    certs = _import_certs()
    paths = certs.CertPaths(instance=f"no-ca-{uuid.uuid4().hex[:8]}", root=tmp_path)
    with pytest.raises(certs.CertsError, match="no certificate authority"):
        certs.issue_server(paths)


def test_issue_client_requires_existing_ca(tmp_path: Path) -> None:
    certs = _import_certs()
    paths = certs.CertPaths(instance=f"no-ca-{uuid.uuid4().hex[:8]}", root=tmp_path)
    with pytest.raises(certs.CertsError, match="no certificate authority"):
        certs.issue_client(paths)


# ---------------------------------------------------------------------------
# create_ca cleans up after a genuine openssl failure.
# ---------------------------------------------------------------------------


def test_create_ca_cleans_up_material_on_openssl_failure(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    certs = _import_certs()
    failing_openssl = shutil.which("false")
    assert failing_openssl is not None, "the 'false' binary must be on PATH for this test"
    monkeypatch.setattr(certs, "OPENSSL_EXECUTABLE", failing_openssl)
    paths = certs.CertPaths(instance=f"broken-openssl-{uuid.uuid4().hex[:8]}", root=tmp_path)

    with pytest.raises(certs.CertsError, match="openssl"):
        certs.create_ca(paths)

    assert not paths.ca_key.exists()
    assert not paths.ca_cert.exists()


# ---------------------------------------------------------------------------
# code_review round 3, BLOCKING A: a pre-existing ca.pem with no matching
# ca-key.pem must survive create_ca's failure UNCHANGED, not merely "still
# present". The pre-flight check used to test only `paths.ca_key.exists()`,
# so a lone stale `ca.pem` sailed past it; `create_ca` then created a fresh
# `ca-key.pem` inside the try block, hit `_prepare_output_file`'s
# `FileExistsError` on the pre-existing `ca.pem`, and the except handler's
# unconditional `paths.ca_cert.unlink(missing_ok=True)` deleted that
# pre-existing `ca.pem` -- exactly the "partially written" material the
# except handler's own docstring claims to scope to, but this file was never
# written by this invocation at all. Asserting mere existence (round 2's
# version of this test) cannot catch a delete-then-nothing-recreated-it
# defect the way asserting the original content survives can. The symmetric
# case (a lone stale `ca-key.pem` with no matching `ca.pem`) is covered by
# the sibling test directly below.
# ---------------------------------------------------------------------------


def test_create_ca_leaves_no_partial_material_when_ca_cert_preexists(tmp_path: Path) -> None:
    certs = _import_certs()
    paths = certs.CertPaths(instance=f"partial-ca-{uuid.uuid4().hex[:8]}", root=tmp_path)
    paths.ca_dir.mkdir(parents=True)
    stale_ca_cert = "stale ca.pem with no matching ca-key.pem"
    paths.ca_cert.write_text(stale_ca_cert, encoding="ascii")

    with pytest.raises(certs.CertsError, match="already exists"):
        certs.create_ca(paths)

    assert not paths.ca_key.exists()
    assert paths.ca_cert.read_text(encoding="ascii") == stale_ca_cert


def test_create_ca_leaves_no_partial_material_when_ca_key_preexists(tmp_path: Path) -> None:
    certs = _import_certs()
    paths = certs.CertPaths(instance=f"partial-ca-{uuid.uuid4().hex[:8]}", root=tmp_path)
    paths.ca_dir.mkdir(parents=True)
    stale_ca_key = "stale ca-key.pem with no matching ca.pem"
    paths.ca_key.write_text(stale_ca_key, encoding="ascii")

    with pytest.raises(certs.CertsError, match="already exists"):
        certs.create_ca(paths)

    assert paths.ca_key.read_text(encoding="ascii") == stale_ca_key
    assert not paths.ca_cert.exists()


# ---------------------------------------------------------------------------
# code_review round 2, BLOCKING part B: `_require_ca` must reject a corrupt
# (empty or unparseable) CA key/certificate by name instead of letting
# `Path.is_file()` alone wave it through to a raw, opaque `openssl` failure.
# This is exactly the state part A's leak above can produce.
# ---------------------------------------------------------------------------


def test_issue_client_rejects_corrupt_zero_byte_ca_key(tmp_path: Path) -> None:
    certs = _import_certs()
    paths = certs.CertPaths(instance=f"corrupt-ca-key-{uuid.uuid4().hex[:8]}", root=tmp_path)
    certs.create_ca(paths)
    paths.ca_key.write_bytes(b"")

    with pytest.raises(certs.CertsError) as excinfo:
        certs.issue_client(paths)

    message = str(excinfo.value)
    assert str(paths.ca_key) in message
    assert "create_ca" in message


# ---------------------------------------------------------------------------
# AC-FUNC-005, AC-TEST-004 error path 2: publication_set.
# ---------------------------------------------------------------------------


def test_publication_set_returns_exactly_the_three_section_5_3_entries() -> None:
    certs = _import_certs()
    entries = certs.publication_set("sandbox")
    observed = {(entry.parameter_path, entry.parameter_type) for entry in entries}
    assert observed == {
        ("/devcontainer/sandbox/tls/server-key.pem", "SecureString"),
        ("/devcontainer/sandbox/tls/server-cert.pem", "SecureString"),
        ("/devcontainer/sandbox/tls/ca.pem", "String"),
    }
    assert not any(entry.parameter_path.endswith("ca-key.pem") for entry in entries)


@pytest.mark.parametrize("ca_key_spelling", ["ca-key.pem", "ca/ca-key.pem"])
def test_publication_set_raises_for_ca_private_key(ca_key_spelling: str) -> None:
    certs = _import_certs()
    with pytest.raises(certs.CertsError) as excinfo:
        certs.publication_set("sandbox", [ca_key_spelling])
    message = str(excinfo.value)
    assert "never leaves the laptop" in message


def test_publication_set_raises_for_any_other_unknown_name() -> None:
    certs = _import_certs()
    with pytest.raises(certs.CertsError, match="not part of the publication set"):
        certs.publication_set("sandbox", ["shell.env"])


def test_prepare_output_file_refuses_overwrite_of_a_pre_existing_file(tmp_path: Path) -> None:
    """The race-condition safety net inside `_prepare_output_file` itself.

    `create_ca`'s own `paths.ca_key.exists()` check normally catches an
    existing authority first, so this exercises `_prepare_output_file`
    directly to prove its own `allow_overwrite=False` guard raises rather
    than silently truncating a file that already exists.
    """
    certs = _import_certs()
    target = tmp_path / "already-there.pem"
    target.write_text("existing", encoding="ascii")
    with pytest.raises(certs.CertsError, match="already exists"):
        certs._prepare_output_file(target, 0o600, allow_overwrite=False)


# ---------------------------------------------------------------------------
# AC-FUNC-005 / security: the CA private key never appears in a public output.
# ---------------------------------------------------------------------------


def test_ca_private_key_material_never_appears_in_public_outputs(
    issued_material: _IssuedMaterial,
) -> None:
    ca_key_bytes = issued_material.paths.ca_key.read_bytes()
    server = issued_material.server
    assert ca_key_bytes not in server.key_pem.encode("ascii")
    assert ca_key_bytes not in server.cert_pem.encode("ascii")
    entries = issued_material.certs.publication_set(issued_material.paths.instance)
    rendered = " ".join(f"{entry.parameter_path} {entry.parameter_type}" for entry in entries)
    assert ca_key_bytes.decode("ascii", errors="ignore") not in rendered


# ---------------------------------------------------------------------------
# AC-TEST-005: no network, no AWS, only openssl, issues into tmp_path.
# ---------------------------------------------------------------------------


def test_certificate_generation_reaches_no_network(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    certs = _import_certs()

    def _forbidden_socket(*_args: object, **_kwargs: object) -> None:
        raise AssertionError("certs.py must not open a network socket")

    monkeypatch.setattr(socket, "socket", _forbidden_socket)
    paths = certs.CertPaths(instance=f"no-network-{uuid.uuid4().hex[:8]}", root=tmp_path)
    certs.create_ca(paths)
    certs.issue_server(paths)
    certs.issue_client(paths)


def test_module_emits_exactly_one_external_command_name() -> None:
    """AC-FUNC-006/AC-TEST-005: the only external command literal is OPENSSL_EXECUTABLE."""
    source = _certs_module_path().read_text(encoding="utf-8")
    tree = ast.parse(source)
    openssl_literals = [
        node
        for node in ast.walk(tree)
        if isinstance(node, ast.Constant) and node.value == "openssl"
    ]
    assert len(openssl_literals) == 1


def test_no_shell_true_anywhere_in_module() -> None:
    """AC-FUNC-006: no subprocess call anywhere in this module passes shell=True."""
    source = _certs_module_path().read_text(encoding="utf-8")
    tree = ast.parse(source)
    shell_true_calls = [
        keyword
        for node in ast.walk(tree)
        if isinstance(node, ast.Call)
        for keyword in node.keywords
        if keyword.arg == "shell"
        and isinstance(keyword.value, ast.Constant)
        and keyword.value.value is True
    ]
    assert shell_true_calls == []


def test_no_stray_files_left_under_root_after_issuance(issued_material: _IssuedMaterial) -> None:
    """AC-FUNC-006: no temporary openssl configuration file (or serial file) is left behind."""
    root = issued_material.paths.root
    assert not list(root.rglob("*.cnf"))
    assert not list(root.rglob("*.srl"))
    assert not list(root.rglob("*.csr"))


# ---------------------------------------------------------------------------
# AC-FINAL-010: functional, end-to-end coverage of the CLI entry point.
# ---------------------------------------------------------------------------


def test_main_create_ca_issue_server_issue_client_publication_set_end_to_end(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    certs = _import_certs()
    instance = f"cli-{uuid.uuid4().hex[:8]}"

    exit_code = certs.main(["create-ca", "--instance", instance, "--root", str(tmp_path)])
    assert exit_code == 0

    exit_code = certs.main(["issue-server", "--instance", instance, "--root", str(tmp_path)])
    assert exit_code == 0

    exit_code = certs.main(["issue-client", "--instance", instance, "--root", str(tmp_path)])
    assert exit_code == 0

    exit_code = certs.main(["publication-set", "--instance", instance])
    assert exit_code == 0
    captured = capsys.readouterr()
    assert f"/devcontainer/{instance}/tls/ca.pem String" in captured.out

    paths = certs.CertPaths(instance=instance, root=tmp_path)
    assert paths.ca_key.is_file()
    assert paths.client_cert.is_file()


def test_main_reports_certs_error_on_stderr_and_exits_nonzero(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    certs = _import_certs()
    instance = f"cli-missing-ca-{uuid.uuid4().hex[:8]}"

    exit_code = certs.main(["issue-client", "--instance", instance, "--root", str(tmp_path)])

    assert exit_code == 1
    captured = capsys.readouterr()
    assert "ERROR" in captured.err


def test_main_create_ca_twice_via_cli_reports_error(tmp_path: Path) -> None:
    certs = _import_certs()
    instance = f"cli-dup-{uuid.uuid4().hex[:8]}"
    assert certs.main(["create-ca", "--instance", instance, "--root", str(tmp_path)]) == 0
    assert certs.main(["create-ca", "--instance", instance, "--root", str(tmp_path)]) == 1


# ---------------------------------------------------------------------------
# code_review round 1, BLOCKING 1/2: `instance` is validated before it ever
# reaches a path composition, a `mkdir`, or an `os.open`, reusing
# `catalog._validate_scope` -- the control catalog.py already carries for the
# identical `/devcontainer/<scope>/` interpolation -- rather than a second,
# independent implementation of the same rule.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "unsafe_instance",
    ["", "../../shared/secrets", "/tmp/escaped-instance", "with/slash", ".."],
)
def test_certpaths_rejects_unsafe_instance_names(tmp_path: Path, unsafe_instance: str) -> None:
    certs = _import_certs()
    with pytest.raises(certs.CertsError, match="instance"):
        certs.CertPaths(instance=unsafe_instance, root=tmp_path)


@pytest.mark.parametrize(
    "unsafe_instance",
    ["", "../../shared/secrets", "/tmp/escaped-instance"],
)
def test_publication_set_rejects_unsafe_instance_names(unsafe_instance: str) -> None:
    certs = _import_certs()
    with pytest.raises(certs.CertsError, match="instance"):
        certs.publication_set(unsafe_instance)


def test_main_create_ca_with_empty_instance_fails_before_creating_anything(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """code_review round 1, BLOCKING 2: an empty --instance must not create anything."""
    certs = _import_certs()

    exit_code = certs.main(["create-ca", "--instance", "", "--root", str(tmp_path)])

    assert exit_code == 1
    captured = capsys.readouterr()
    assert "ERROR" in captured.err
    assert list(tmp_path.iterdir()) == []


# ---------------------------------------------------------------------------
# code_review round 1, BLOCKING 3: an `OSError` from directory or file
# creation must surface as `certs.CertsError`, never an uncaught stack trace,
# matching `main`'s own documented error contract.
# ---------------------------------------------------------------------------


def test_main_create_ca_reports_certserror_when_root_is_unwritable(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Reproduces the reviewer's own demonstration: an unwritable --root must
    fail as CertsError, not an uncaught PermissionError with a stack trace."""
    certs = _import_certs()
    unwritable_root = tmp_path / "unwritable-root"
    unwritable_root.mkdir(mode=0o755)
    unwritable_root.chmod(0o500)
    instance = f"unwritable-{uuid.uuid4().hex[:8]}"

    try:
        exit_code = certs.main(
            ["create-ca", "--instance", instance, "--root", str(unwritable_root)]
        )
    finally:
        unwritable_root.chmod(0o755)

    assert exit_code == 1
    captured = capsys.readouterr()
    assert "ERROR" in captured.err
    assert "Traceback" not in captured.err


def test_ensure_dir_translates_oserror_into_certserror(tmp_path: Path) -> None:
    certs = _import_certs()
    unwritable_root = tmp_path / "unwritable-root"
    unwritable_root.mkdir(mode=0o755)
    unwritable_root.chmod(0o500)
    target = unwritable_root / "instance-dir"

    try:
        with pytest.raises(certs.CertsError, match="cannot create"):
            certs._ensure_dir(target, 0o700)
    finally:
        unwritable_root.chmod(0o755)


def test_prepare_output_file_translates_oserror_from_open_into_certserror(
    tmp_path: Path,
) -> None:
    certs = _import_certs()
    unwritable_dir = tmp_path / "unwritable"
    unwritable_dir.mkdir(mode=0o755)
    unwritable_dir.chmod(0o500)
    target = unwritable_dir / "out.pem"

    try:
        with pytest.raises(certs.CertsError, match="cannot create"):
            certs._prepare_output_file(target, 0o600, allow_overwrite=True)
    finally:
        unwritable_dir.chmod(0o755)


def test_prepare_output_file_translates_oserror_from_chmod_into_certserror(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """The second `os.chmod` call, after a successful `os.open`, is translated too."""
    certs = _import_certs()
    target = tmp_path / "out.pem"

    def _raise_chmod_error(*_args: object, **_kwargs: object) -> None:
        raise OSError("simulated chmod failure")

    monkeypatch.setattr(certs.os, "chmod", _raise_chmod_error)

    with pytest.raises(certs.CertsError, match="set permissions on"):
        certs._prepare_output_file(target, 0o600, allow_overwrite=True)


def test_require_parseable_ca_component_translates_oserror_into_certserror(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """`_require_parseable_ca_component`'s own `read_bytes` failure is translated
    the same way `_ensure_dir` and `_prepare_output_file` translate theirs
    (code_review, this unit, round 1: BLOCKING 3's guarantee, extended to
    round 2's new corruption check)."""
    certs = _import_certs()
    target = tmp_path / "ca.pem"
    target.write_bytes(b"-----BEGIN CERTIFICATE-----\n")

    def _raise_read_error(*_args: object, **_kwargs: object) -> bytes:
        raise OSError("simulated read failure")

    monkeypatch.setattr(certs.Path, "read_bytes", _raise_read_error)

    with pytest.raises(certs.CertsError, match="cannot read"):
        certs._require_parseable_ca_component(target, "sandbox")


# ---------------------------------------------------------------------------
# code_review round 1, WARN 5: `_issue_certificate` cleans up a truncated key
# or certificate at the real material path on a mid-issuance openssl
# failure, the same guarantee `create_ca` already gives its own material.
# ---------------------------------------------------------------------------


def test_issue_client_cleans_up_material_on_openssl_failure_mid_issuance(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    certs = _import_certs()
    paths = certs.CertPaths(instance=f"issue-fail-{uuid.uuid4().hex[:8]}", root=tmp_path)
    certs.create_ca(paths)
    failing_openssl = shutil.which("false")
    assert failing_openssl is not None, "the 'false' binary must be on PATH for this test"
    monkeypatch.setattr(certs, "OPENSSL_EXECUTABLE", failing_openssl)

    with pytest.raises(certs.CertsError, match="openssl"):
        certs.issue_client(paths)

    assert not paths.client_key.exists()
    assert not paths.client_cert.exists()


# ---------------------------------------------------------------------------
# code_review round 3, WARN C: rotating an existing, valid client certificate
# must never strand the developer without ANY client credential. The
# pre-round-3 implementation truncated `key_out` via
# `_prepare_output_file(allow_overwrite=True)` before the first `openssl`
# call, then unlinked both `key_out` and `cert_out` in the `except CertsError`
# handler, so a failing `openssl` during a rotation destroyed the previously
# valid key and certificate a running instance still trusted, with nothing
# to replace them. `_issue_certificate` now writes into a temporary
# directory on the SAME filesystem as the final destination and commits both
# files with `os.replace` only after every `openssl` call has succeeded, the
# same commit-only-on-success guarantee `create_ca` gives its own material,
# mirroring the temporary-directory pattern `issue_server` already uses.
# ---------------------------------------------------------------------------


def test_issue_client_rotation_does_not_strand_developer_without_credential(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    certs = _import_certs()
    paths = certs.CertPaths(instance=f"issue-rotate-fail-{uuid.uuid4().hex[:8]}", root=tmp_path)
    certs.create_ca(paths)
    certs.issue_client(paths)
    original_key = paths.client_key.read_text(encoding="ascii")
    original_cert = paths.client_cert.read_text(encoding="ascii")

    failing_openssl = shutil.which("false")
    assert failing_openssl is not None, "the 'false' binary must be on PATH for this test"
    monkeypatch.setattr(certs, "OPENSSL_EXECUTABLE", failing_openssl)

    with pytest.raises(certs.CertsError, match="openssl"):
        certs.issue_client(paths)

    assert paths.client_key.read_text(encoding="ascii") == original_key
    assert paths.client_cert.read_text(encoding="ascii") == original_cert


# ---------------------------------------------------------------------------
# code_review round 1, WARN 4: PARAMETER_ROOT and SECURE_STRING_TYPE are the
# same values catalog.py already defines, reused rather than redeclared.
# ---------------------------------------------------------------------------


def test_parameter_root_and_secure_string_type_are_reused_from_catalog() -> None:
    """Values must match catalog AND the source must reference catalog's
    attributes rather than redeclaring the same literals independently --
    equal values alone would not catch a second, independent definition
    that merely happens to agree with catalog's today."""
    certs = _import_certs()
    catalog = importlib.import_module("devcontainer_config.catalog")
    assert certs.PARAMETER_ROOT == catalog.PATH_ROOT
    assert certs.SECURE_STRING_TYPE == catalog.SECURE_STRING_TYPE

    source = _certs_module_path().read_text(encoding="utf-8")
    tree = ast.parse(source)
    reused_from_catalog = {
        target.id
        for node in ast.walk(tree)
        if isinstance(node, ast.Assign)
        for target in node.targets
        if isinstance(target, ast.Name)
        and target.id in {"PARAMETER_ROOT", "SECURE_STRING_TYPE"}
        and isinstance(node.value, ast.Attribute)
        and isinstance(node.value.value, ast.Name)
        and node.value.value.id == "catalog"
    }
    assert reused_from_catalog == {"PARAMETER_ROOT", "SECURE_STRING_TYPE"}
