"""Tests for devcontainer_config.certs (spec Section 4.5; E6-F1-S1-T1).

The `devcontainer_config.certs` import is deferred into function bodies (via
`_import_certs`) instead of done once at module scope, for the same reason
`tests/test_repo.py` and `tests/test_hostprobe.py` document: the TDD RED gate
stashes this unit's own production-source files -- `certs.py` is new, added
by this task -- and re-runs a single named test node. A module-level `from
devcontainer_config.certs import ...` would fail COLLECTION for the whole
file (pytest exit code 2, no test outcome recorded) instead of failing the
one named test for the real reason: the module is missing. `_certs_module_path`
reads the file by path rather than importing it, for the identical reason.

Every certificate this file inspects is generated by the module under test,
into a fresh directory under `tmp_path`, and inspected by shelling out to the
real `openssl x509 -noout -text` (SANs, extended key usage) or `-startdate
-enddate` (lifetimes) -- never by re-reading the arguments this module
passed to its own `openssl` calls, which is what makes the SAN and
`clientAuth`/`serverAuth` assertions genuine parses of generated material
(AC-5.2, AC-TEST-001, AC-TEST-002) rather than a test that could pass even if
the generated certificate were wrong.

`issued_material` is a module-scoped fixture: one CA, one server certificate
and one client certificate, issued once into a `tmp_path_factory` directory
and reused by every read-only assertion below (SANs, key usage, modes,
default lifetimes, the "CA already exists" error, and the no-network and
no-stray-file checks). Tests that need a *different* environment --
`CERT_CLIENT_DAYS` overridden, `openssl` missing, no CA created yet -- build
their own fresh `CertPaths` under a function-scoped `tmp_path` instead of
sharing this fixture, since mutating shared state there would make one
test's outcome depend on another's execution order.
"""

from __future__ import annotations

import ast
import datetime
import hashlib
import importlib
import shutil
import socket
import stat
import subprocess
import sys
import uuid
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType

import pytest


def _import_certs() -> ModuleType:
    """Import devcontainer_config.certs from inside a function body.

    See the module docstring for why this is not a module-level import.
    """
    return importlib.import_module("devcontainer_config.certs")


def _certs_module_path() -> Path:
    return (
        Path(__file__).resolve().parents[1]
        / ".claude"
        / "plugins"
        / "devcontainer"
        / "scripts"
        / "devcontainer_config"
        / "certs.py"
    )


def _openssl_text(pem_path: Path) -> str:
    """`openssl x509 -noout -text` over a real generated certificate file."""
    result = subprocess.run(
        ["openssl", "x509", "-noout", "-text", "-in", str(pem_path)],
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout


def _openssl_text_from_pem(pem_text: str, tmp_path: Path, name: str) -> str:
    """`openssl x509 -noout -text` over PEM text that has no file of its own.

    `issue_server`'s return value is never written under the material root
    (spec Section 5.5 has no server-key/server-cert row), so a test that
    wants to parse it writes the PEM text to a throwaway path under its own
    `tmp_path` purely to hand it to `openssl` -- this is a test-only
    convenience, not a persistence path the production module ever takes.
    """
    scratch_path = tmp_path / name
    scratch_path.write_text(pem_text, encoding="ascii")
    return _openssl_text(scratch_path)


def _lifetime_days(pem_path: Path) -> int:
    """`notAfter - notBefore`, in whole days, for a real generated certificate."""
    result = subprocess.run(
        ["openssl", "x509", "-noout", "-startdate", "-enddate", "-in", str(pem_path)],
        capture_output=True,
        text=True,
        check=True,
    )
    dates: dict[str, datetime.datetime] = {}
    for line in result.stdout.splitlines():
        key, _, value = line.partition("=")
        dates[key] = datetime.datetime.strptime(value.strip(), "%b %d %H:%M:%S %Y %Z")
    delta = dates["notAfter"] - dates["notBefore"]
    return delta.days


def _file_mode(path: Path) -> int:
    return stat.S_IMODE(path.stat().st_mode)


def _serial(cert_path: Path) -> str:
    """A real generated certificate's serial number, via `openssl x509 -noout -serial`."""
    result = subprocess.run(
        ["openssl", "x509", "-noout", "-serial", "-in", str(cert_path)],
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def _verifies_against_ca(cert_path: Path, ca_cert_path: Path) -> bool:
    """Whether `cert_path` verifies against `ca_cert_path`, via `openssl verify -CAfile`."""
    result = subprocess.run(
        ["openssl", "verify", "-CAfile", str(ca_cert_path), str(cert_path)],
        capture_output=True,
        text=True,
        check=False,
    )
    return result.returncode == 0


def _hash_instance_directory(instance_dir: Path) -> dict[str, str]:
    """Every regular file's sha256 hash under `instance_dir`, keyed by its relative path."""
    return {
        str(path.relative_to(instance_dir)): hashlib.sha256(path.read_bytes()).hexdigest()
        for path in sorted(instance_dir.rglob("*"))
        if path.is_file()
    }


@dataclass(frozen=True)
class _IssuedMaterial:
    certs: ModuleType
    paths: object
    server: object


@pytest.fixture(scope="module")
def issued_material(tmp_path_factory: pytest.TempPathFactory) -> _IssuedMaterial:
    """One CA, one server certificate and one client certificate, issued once."""
    certs = _import_certs()
    root = tmp_path_factory.mktemp("certs-root")
    instance = f"test-{uuid.uuid4().hex[:8]}"
    paths = certs.CertPaths(instance=instance, root=root)
    certs.create_ca(paths)
    server = certs.issue_server(paths)
    certs.issue_client(paths)
    return _IssuedMaterial(certs=certs, paths=paths, server=server)


# ---------------------------------------------------------------------------
# DEFAULT_CERTS_ROOT (E8-F1-S1-T1 round 2, code_review BLOCKING 2): a single
# derivation must own spec Section 9's certificate-directory row, so an
# operator who sets DOCKER_CONFIG never has certificates written under one
# directory while devcontainer_config.instances.certs_dir addresses another.
# ---------------------------------------------------------------------------


def test_default_certs_root_is_sourced_from_instances_certs_root() -> None:
    certs = _import_certs()
    instances = importlib.import_module("devcontainer_config.instances")

    assert certs.DEFAULT_CERTS_ROOT == instances.certs_root()


def test_default_certs_root_reflects_docker_config_on_a_fresh_import(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """`DEFAULT_CERTS_ROOT` is a module-level constant, computed once at import (unchanged
    behavior from before this delegation existed), so this proves it honors `DOCKER_CONFIG`
    at that computation rather than reading the pre-`DOCKER_CONFIG` `~/.docker/certs` default.

    test_review round 2, BLOCKING (test isolation): the original version of this test
    popped both modules and re-imported `certs` inside `finally` while `DOCKER_CONFIG`
    was still monkeypatched to this test's own `tmp_path`, leaving a poisoned module
    object in `sys.modules` -- one whose `DEFAULT_CERTS_ROOT` pointed at a directory
    pytest later deletes, and whose identity differs from the one
    `devcontainer_config.transport` captured via its own `from devcontainer_config
    import certs` at first import. Restoring `sys.modules["devcontainer_config.certs"]`
    alone is not sufficient: Python's import machinery also sets the parent package's
    own attribute (`sys.modules["devcontainer_config"].certs`) to whatever module object
    was most recently imported under that name, and a later `from devcontainer_config
    import certs` (such as `devcontainer_config.transport`'s own module-level import)
    resolves through that package attribute first, not through `sys.modules` directly.
    Both must be restored to the exact original objects, or a module imported after this
    test still observes the poisoned one.
    """
    module_names = ("devcontainer_config.certs", "devcontainer_config.instances")
    saved_modules = {name: sys.modules.get(name) for name in module_names}
    package = sys.modules["devcontainer_config"]
    saved_package_attrs = {
        name: getattr(package, name.rsplit(".", 1)[-1], None) for name in module_names
    }
    moved_docker_home = tmp_path / "moved-docker-home"
    monkeypatch.setenv("DOCKER_CONFIG", str(moved_docker_home))
    for module_name in module_names:
        sys.modules.pop(module_name, None)

    try:
        certs = importlib.import_module("devcontainer_config.certs")
        assert certs.DEFAULT_CERTS_ROOT == moved_docker_home / "certs"
    finally:
        # Unset DOCKER_CONFIG before restoring anything, so no import triggered by the
        # restore below (or by any later test) can observe this test's environment.
        monkeypatch.delenv("DOCKER_CONFIG", raising=False)
        for module_name in module_names:
            sys.modules.pop(module_name, None)
            attr_name = module_name.rsplit(".", 1)[-1]
            original = saved_modules[module_name]
            original_attr = saved_package_attrs[module_name]
            if original is not None:
                sys.modules[module_name] = original
            if original_attr is not None:
                setattr(package, attr_name, original_attr)


# ---------------------------------------------------------------------------
# AC-TEST-001 / AC-TEST-002: SANs and extended key usage, parsed for real.
# ---------------------------------------------------------------------------


def test_server_certificate_has_required_sans_and_no_others(
    issued_material: _IssuedMaterial, tmp_path: Path
) -> None:
    text = _openssl_text_from_pem(issued_material.server.cert_pem, tmp_path, "server-cert.pem")
    san_line = next(line for line in text.splitlines() if "Subject Alternative Name" in line)
    san_values_line = text.splitlines()[text.splitlines().index(san_line) + 1].strip()
    assert san_values_line == "IP Address:127.0.0.1, DNS:localhost"


@pytest.mark.parametrize(
    "expected_usage,role",
    [("TLS Web Server Authentication", "server"), ("TLS Web Client Authentication", "client")],
)
def test_extended_key_usage_matches_role(
    issued_material: _IssuedMaterial, tmp_path: Path, expected_usage: str, role: str
) -> None:
    if role == "server":
        text = _openssl_text_from_pem(issued_material.server.cert_pem, tmp_path, "server-cert.pem")
    else:
        text = _openssl_text(issued_material.paths.client_cert)
    assert expected_usage in text


# ---------------------------------------------------------------------------
# AC-TEST-003: every file/directory mode, and every default lifetime.
# ---------------------------------------------------------------------------


def test_instance_directory_mode_is_0700(issued_material: _IssuedMaterial) -> None:
    assert _file_mode(issued_material.paths.instance_dir) == 0o700


@pytest.mark.parametrize(
    "path_name,expected_mode",
    [
        ("ca_key", 0o600),
        ("ca_cert", 0o644),
        ("client_key", 0o600),
        ("client_cert", 0o644),
    ],
)
def test_material_file_mode(
    issued_material: _IssuedMaterial, path_name: str, expected_mode: int
) -> None:
    path = getattr(issued_material.paths, path_name)
    assert _file_mode(path) == expected_mode


@pytest.mark.parametrize(
    "path_name,expected_days",
    [("ca_cert", 3650), ("client_cert", 90)],
)
def test_default_lifetime_days(
    issued_material: _IssuedMaterial, path_name: str, expected_days: int
) -> None:
    path = getattr(issued_material.paths, path_name)
    assert _lifetime_days(path) == expected_days


def test_default_server_lifetime_days(issued_material: _IssuedMaterial, tmp_path: Path) -> None:
    scratch_path = tmp_path / "server-cert-for-lifetime.pem"
    scratch_path.write_text(issued_material.server.cert_pem, encoding="ascii")
    assert _lifetime_days(scratch_path) == 365


def test_client_lifetime_follows_cert_client_days_override(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """CERT_CLIENT_DAYS is honored, proving the lifetime is not hardcoded at any call site."""
    certs = _import_certs()
    monkeypatch.setenv("CERT_CLIENT_DAYS", "30")
    instance = f"override-{uuid.uuid4().hex[:8]}"
    paths = certs.CertPaths(instance=instance, root=tmp_path)
    certs.create_ca(paths)
    certs.issue_client(paths)
    assert _lifetime_days(paths.client_cert) == 30


# ---------------------------------------------------------------------------
# AC-FUNC-004: invalid lifetime environment values fail fast.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("raw_value", ["not-a-number", "0", "-5"])
def test_invalid_cert_ca_days_raises(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, raw_value: str
) -> None:
    certs = _import_certs()
    monkeypatch.setenv("CERT_CA_DAYS", raw_value)
    paths = certs.CertPaths(instance=f"bad-days-{uuid.uuid4().hex[:8]}", root=tmp_path)
    with pytest.raises(certs.CertsError, match="CERT_CA_DAYS"):
        certs.create_ca(paths)


# ---------------------------------------------------------------------------
# AC-FUNC-001, AC-TEST-004 error path 3: create_ca never silently overwrites.
# ---------------------------------------------------------------------------


def test_create_ca_twice_raises_naming_existing_path(issued_material: _IssuedMaterial) -> None:
    certs = issued_material.certs
    with pytest.raises(certs.CertsError) as excinfo:
        certs.create_ca(issued_material.paths)
    message = str(excinfo.value)
    assert "already exists" in message
    assert str(issued_material.paths.ca_key) in message


# ---------------------------------------------------------------------------
# AC-TEST-004 error path 1: openssl missing from PATH, nothing created.
# ---------------------------------------------------------------------------


def test_openssl_missing_fails_before_creating_anything(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    certs = _import_certs()
    monkeypatch.setattr(certs.shutil, "which", lambda _name: None)
    paths = certs.CertPaths(instance=f"no-openssl-{uuid.uuid4().hex[:8]}", root=tmp_path)

    with pytest.raises(certs.CertsError, match="openssl"):
        certs.create_ca(paths)

    assert not paths.instance_dir.exists()


# ---------------------------------------------------------------------------
# create_ca / issue_server / issue_client both require an existing CA.
# ---------------------------------------------------------------------------


def test_issue_server_requires_existing_ca(tmp_path: Path) -> None:
    certs = _import_certs()
    paths = certs.CertPaths(instance=f"no-ca-{uuid.uuid4().hex[:8]}", root=tmp_path)
    with pytest.raises(certs.CertsError, match="no certificate authority"):
        certs.issue_server(paths)


def test_issue_client_requires_existing_ca(tmp_path: Path) -> None:
    certs = _import_certs()
    paths = certs.CertPaths(instance=f"no-ca-{uuid.uuid4().hex[:8]}", root=tmp_path)
    with pytest.raises(certs.CertsError, match="no certificate authority"):
        certs.issue_client(paths)


# ---------------------------------------------------------------------------
# create_ca cleans up after a genuine openssl failure.
# ---------------------------------------------------------------------------


def test_create_ca_cleans_up_material_on_openssl_failure(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    certs = _import_certs()
    failing_openssl = shutil.which("false")
    assert failing_openssl is not None, "the 'false' binary must be on PATH for this test"
    monkeypatch.setattr(certs, "OPENSSL_EXECUTABLE", failing_openssl)
    paths = certs.CertPaths(instance=f"broken-openssl-{uuid.uuid4().hex[:8]}", root=tmp_path)

    with pytest.raises(certs.CertsError, match="openssl"):
        certs.create_ca(paths)

    assert not paths.ca_key.exists()
    assert not paths.ca_cert.exists()


# ---------------------------------------------------------------------------
# code_review round 3, BLOCKING A: a pre-existing ca.pem with no matching
# ca-key.pem must survive create_ca's failure UNCHANGED, not merely "still
# present". The pre-flight check used to test only `paths.ca_key.exists()`,
# so a lone stale `ca.pem` sailed past it; `create_ca` then created a fresh
# `ca-key.pem` inside the try block, hit `_prepare_output_file`'s
# `FileExistsError` on the pre-existing `ca.pem`, and the except handler's
# unconditional `paths.ca_cert.unlink(missing_ok=True)` deleted that
# pre-existing `ca.pem` -- exactly the "partially written" material the
# except handler's own docstring claims to scope to, but this file was never
# written by this invocation at all. Asserting mere existence (round 2's
# version of this test) cannot catch a delete-then-nothing-recreated-it
# defect the way asserting the original content survives can. The symmetric
# case (a lone stale `ca-key.pem` with no matching `ca.pem`) is covered by
# the sibling test directly below.
# ---------------------------------------------------------------------------


def test_create_ca_leaves_no_partial_material_when_ca_cert_preexists(tmp_path: Path) -> None:
    certs = _import_certs()
    paths = certs.CertPaths(instance=f"partial-ca-{uuid.uuid4().hex[:8]}", root=tmp_path)
    paths.ca_dir.mkdir(parents=True)
    stale_ca_cert = "stale ca.pem with no matching ca-key.pem"
    paths.ca_cert.write_text(stale_ca_cert, encoding="ascii")

    with pytest.raises(certs.CertsError, match="already exists"):
        certs.create_ca(paths)

    assert not paths.ca_key.exists()
    assert paths.ca_cert.read_text(encoding="ascii") == stale_ca_cert


def test_create_ca_leaves_no_partial_material_when_ca_key_preexists(tmp_path: Path) -> None:
    certs = _import_certs()
    paths = certs.CertPaths(instance=f"partial-ca-{uuid.uuid4().hex[:8]}", root=tmp_path)
    paths.ca_dir.mkdir(parents=True)
    stale_ca_key = "stale ca-key.pem with no matching ca.pem"
    paths.ca_key.write_text(stale_ca_key, encoding="ascii")

    with pytest.raises(certs.CertsError, match="already exists"):
        certs.create_ca(paths)

    assert paths.ca_key.read_text(encoding="ascii") == stale_ca_key
    assert not paths.ca_cert.exists()


# ---------------------------------------------------------------------------
# code_review round 2, BLOCKING part B: `_require_ca` must reject a corrupt
# (empty or unparseable) CA key/certificate by name instead of letting
# `Path.is_file()` alone wave it through to a raw, opaque `openssl` failure.
# This is exactly the state part A's leak above can produce.
# ---------------------------------------------------------------------------


def test_issue_client_rejects_corrupt_zero_byte_ca_key(tmp_path: Path) -> None:
    certs = _import_certs()
    paths = certs.CertPaths(instance=f"corrupt-ca-key-{uuid.uuid4().hex[:8]}", root=tmp_path)
    certs.create_ca(paths)
    paths.ca_key.write_bytes(b"")

    with pytest.raises(certs.CertsError) as excinfo:
        certs.issue_client(paths)

    message = str(excinfo.value)
    assert str(paths.ca_key) in message
    assert "create_ca" in message


# ---------------------------------------------------------------------------
# AC-FUNC-005, AC-TEST-004 error path 2: publication_set.
# ---------------------------------------------------------------------------


def test_publication_set_returns_exactly_the_three_section_5_3_entries() -> None:
    certs = _import_certs()
    entries = certs.publication_set("sandbox")
    observed = {(entry.parameter_path, entry.parameter_type) for entry in entries}
    assert observed == {
        ("/devcontainer/sandbox/tls/server-key.pem", "SecureString"),
        ("/devcontainer/sandbox/tls/server-cert.pem", "SecureString"),
        ("/devcontainer/sandbox/tls/ca.pem", "String"),
    }
    assert not any(entry.parameter_path.endswith("ca-key.pem") for entry in entries)


@pytest.mark.parametrize("ca_key_spelling", ["ca-key.pem", "ca/ca-key.pem"])
def test_publication_set_raises_for_ca_private_key(ca_key_spelling: str) -> None:
    certs = _import_certs()
    with pytest.raises(certs.CertsError) as excinfo:
        certs.publication_set("sandbox", [ca_key_spelling])
    message = str(excinfo.value)
    assert "never leaves the laptop" in message


def test_publication_set_raises_for_any_other_unknown_name() -> None:
    certs = _import_certs()
    with pytest.raises(certs.CertsError, match="not part of the publication set"):
        certs.publication_set("sandbox", ["shell.env"])


def test_prepare_output_file_refuses_overwrite_of_a_pre_existing_file(tmp_path: Path) -> None:
    """The race-condition safety net inside `_prepare_output_file` itself.

    `create_ca`'s own `paths.ca_key.exists()` check normally catches an
    existing authority first, so this exercises `_prepare_output_file`
    directly to prove its own `allow_overwrite=False` guard raises rather
    than silently truncating a file that already exists.
    """
    certs = _import_certs()
    target = tmp_path / "already-there.pem"
    target.write_text("existing", encoding="ascii")
    with pytest.raises(certs.CertsError, match="already exists"):
        certs._prepare_output_file(target, 0o600, allow_overwrite=False)


# ---------------------------------------------------------------------------
# AC-FUNC-005 / security: the CA private key never appears in a public output.
# ---------------------------------------------------------------------------


def test_ca_private_key_material_never_appears_in_public_outputs(
    issued_material: _IssuedMaterial,
) -> None:
    ca_key_bytes = issued_material.paths.ca_key.read_bytes()
    server = issued_material.server
    assert ca_key_bytes not in server.key_pem.encode("ascii")
    assert ca_key_bytes not in server.cert_pem.encode("ascii")
    entries = issued_material.certs.publication_set(issued_material.paths.instance)
    rendered = " ".join(f"{entry.parameter_path} {entry.parameter_type}" for entry in entries)
    assert ca_key_bytes.decode("ascii", errors="ignore") not in rendered


# ---------------------------------------------------------------------------
# AC-TEST-005: no network, no AWS, only openssl, issues into tmp_path.
# ---------------------------------------------------------------------------


def test_certificate_generation_reaches_no_network(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    certs = _import_certs()

    def _forbidden_socket(*_args: object, **_kwargs: object) -> None:
        raise AssertionError("certs.py must not open a network socket")

    monkeypatch.setattr(socket, "socket", _forbidden_socket)
    paths = certs.CertPaths(instance=f"no-network-{uuid.uuid4().hex[:8]}", root=tmp_path)
    certs.create_ca(paths)
    certs.issue_server(paths)
    certs.issue_client(paths)


def test_module_emits_exactly_one_external_command_name() -> None:
    """AC-FUNC-006/AC-TEST-005: the only external command literal is OPENSSL_EXECUTABLE."""
    source = _certs_module_path().read_text(encoding="utf-8")
    tree = ast.parse(source)
    openssl_literals = [
        node
        for node in ast.walk(tree)
        if isinstance(node, ast.Constant) and node.value == "openssl"
    ]
    assert len(openssl_literals) == 1


def test_no_shell_true_anywhere_in_module() -> None:
    """AC-FUNC-006: no subprocess call anywhere in this module passes shell=True."""
    source = _certs_module_path().read_text(encoding="utf-8")
    tree = ast.parse(source)
    shell_true_calls = [
        keyword
        for node in ast.walk(tree)
        if isinstance(node, ast.Call)
        for keyword in node.keywords
        if keyword.arg == "shell"
        and isinstance(keyword.value, ast.Constant)
        and keyword.value.value is True
    ]
    assert shell_true_calls == []


def test_no_stray_files_left_under_root_after_issuance(issued_material: _IssuedMaterial) -> None:
    """AC-FUNC-006: no temporary openssl configuration file (or serial file) is left behind."""
    root = issued_material.paths.root
    assert not list(root.rglob("*.cnf"))
    assert not list(root.rglob("*.srl"))
    assert not list(root.rglob("*.csr"))


# ---------------------------------------------------------------------------
# AC-FINAL-010: functional, end-to-end coverage of the CLI entry point.
# ---------------------------------------------------------------------------


def test_main_create_ca_issue_server_issue_client_publication_set_end_to_end(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    certs = _import_certs()
    instance = f"cli-{uuid.uuid4().hex[:8]}"

    exit_code = certs.main(["create-ca", "--instance", instance, "--root", str(tmp_path)])
    assert exit_code == 0

    exit_code = certs.main(["issue-server", "--instance", instance, "--root", str(tmp_path)])
    assert exit_code == 0

    exit_code = certs.main(["issue-client", "--instance", instance, "--root", str(tmp_path)])
    assert exit_code == 0

    exit_code = certs.main(["publication-set", "--instance", instance])
    assert exit_code == 0
    captured = capsys.readouterr()
    assert f"/devcontainer/{instance}/tls/ca.pem String" in captured.out

    paths = certs.CertPaths(instance=instance, root=tmp_path)
    assert paths.ca_key.is_file()
    assert paths.client_cert.is_file()


def test_main_reports_certs_error_on_stderr_and_exits_nonzero(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    certs = _import_certs()
    instance = f"cli-missing-ca-{uuid.uuid4().hex[:8]}"

    exit_code = certs.main(["issue-client", "--instance", instance, "--root", str(tmp_path)])

    assert exit_code == 1
    captured = capsys.readouterr()
    assert "ERROR" in captured.err


def test_main_create_ca_twice_via_cli_reports_error(tmp_path: Path) -> None:
    certs = _import_certs()
    instance = f"cli-dup-{uuid.uuid4().hex[:8]}"
    assert certs.main(["create-ca", "--instance", instance, "--root", str(tmp_path)]) == 0
    assert certs.main(["create-ca", "--instance", instance, "--root", str(tmp_path)]) == 1


# ---------------------------------------------------------------------------
# code_review round 1, BLOCKING 1/2: `instance` is validated before it ever
# reaches a path composition, a `mkdir`, or an `os.open`, reusing
# `instances.validate_name` -- the single owner spec Section 4.5 assigns the
# naming rule -- rather than a second, independent implementation of the
# same rule.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "unsafe_instance",
    ["", "../../shared/secrets", "/tmp/escaped-instance", "with/slash", ".."],
)
def test_certpaths_rejects_unsafe_instance_names(tmp_path: Path, unsafe_instance: str) -> None:
    certs = _import_certs()
    with pytest.raises(certs.CertsError, match="instance"):
        certs.CertPaths(instance=unsafe_instance, root=tmp_path)


def test_certpaths_rejects_an_over_length_instance_name_matching_instances_bound(
    tmp_path: Path,
) -> None:
    """code_review round 2, WARN (DRY): before this fix `_validate_instance` delegated
    only to `catalog._validate_scope`, which enforces no length bound, so a 64+ character
    instance name was accepted by `CertPaths.instance_dir` and rejected by
    `instances.certs_dir` for the identical directory -- two validators of the same
    concept disagreeing on the same value. Delegating to `instances.validate_name`
    instead gives the naming rule a single owner (spec Section 4.5) and this length
    bound with it.
    """
    certs = _import_certs()
    instances = importlib.import_module("devcontainer_config.instances")
    over_length_instance = "a" * (instances.MAX_INSTANCE_NAME_LENGTH + 1)

    with pytest.raises(certs.CertsError, match="instance"):
        certs.CertPaths(instance=over_length_instance, root=tmp_path)


@pytest.mark.parametrize(
    "unsafe_instance",
    ["", "../../shared/secrets", "/tmp/escaped-instance"],
)
def test_publication_set_rejects_unsafe_instance_names(unsafe_instance: str) -> None:
    certs = _import_certs()
    with pytest.raises(certs.CertsError, match="instance"):
        certs.publication_set(unsafe_instance)


def test_main_create_ca_with_empty_instance_fails_before_creating_anything(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """code_review round 1, BLOCKING 2: an empty --instance must not create anything."""
    certs = _import_certs()

    exit_code = certs.main(["create-ca", "--instance", "", "--root", str(tmp_path)])

    assert exit_code == 1
    captured = capsys.readouterr()
    assert "ERROR" in captured.err
    assert list(tmp_path.iterdir()) == []


# ---------------------------------------------------------------------------
# code_review round 1, BLOCKING 3: an `OSError` from directory or file
# creation must surface as `certs.CertsError`, never an uncaught stack trace,
# matching `main`'s own documented error contract.
# ---------------------------------------------------------------------------


def test_main_create_ca_reports_certserror_when_root_is_unwritable(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Reproduces the reviewer's own demonstration: an unwritable --root must
    fail as CertsError, not an uncaught PermissionError with a stack trace."""
    certs = _import_certs()
    unwritable_root = tmp_path / "unwritable-root"
    unwritable_root.mkdir(mode=0o755)
    unwritable_root.chmod(0o500)
    instance = f"unwritable-{uuid.uuid4().hex[:8]}"

    try:
        exit_code = certs.main(
            ["create-ca", "--instance", instance, "--root", str(unwritable_root)]
        )
    finally:
        unwritable_root.chmod(0o755)

    assert exit_code == 1
    captured = capsys.readouterr()
    assert "ERROR" in captured.err
    assert "Traceback" not in captured.err


def test_ensure_dir_translates_oserror_into_certserror(tmp_path: Path) -> None:
    certs = _import_certs()
    unwritable_root = tmp_path / "unwritable-root"
    unwritable_root.mkdir(mode=0o755)
    unwritable_root.chmod(0o500)
    target = unwritable_root / "instance-dir"

    try:
        with pytest.raises(certs.CertsError, match="cannot create"):
            certs._ensure_dir(target, 0o700)
    finally:
        unwritable_root.chmod(0o755)


def test_prepare_output_file_translates_oserror_from_open_into_certserror(
    tmp_path: Path,
) -> None:
    certs = _import_certs()
    unwritable_dir = tmp_path / "unwritable"
    unwritable_dir.mkdir(mode=0o755)
    unwritable_dir.chmod(0o500)
    target = unwritable_dir / "out.pem"

    try:
        with pytest.raises(certs.CertsError, match="cannot create"):
            certs._prepare_output_file(target, 0o600, allow_overwrite=True)
    finally:
        unwritable_dir.chmod(0o755)


def test_prepare_output_file_translates_oserror_from_chmod_into_certserror(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """The second `os.chmod` call, after a successful `os.open`, is translated too."""
    certs = _import_certs()
    target = tmp_path / "out.pem"

    def _raise_chmod_error(*_args: object, **_kwargs: object) -> None:
        raise OSError("simulated chmod failure")

    monkeypatch.setattr(certs.os, "chmod", _raise_chmod_error)

    with pytest.raises(certs.CertsError, match="set permissions on"):
        certs._prepare_output_file(target, 0o600, allow_overwrite=True)


def test_require_parseable_ca_component_translates_oserror_into_certserror(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """`_require_parseable_ca_component`'s own `read_bytes` failure is translated
    the same way `_ensure_dir` and `_prepare_output_file` translate theirs
    (code_review, this unit, round 1: BLOCKING 3's guarantee, extended to
    round 2's new corruption check)."""
    certs = _import_certs()
    target = tmp_path / "ca.pem"
    target.write_bytes(b"-----BEGIN CERTIFICATE-----\n")

    def _raise_read_error(*_args: object, **_kwargs: object) -> bytes:
        raise OSError("simulated read failure")

    monkeypatch.setattr(certs.Path, "read_bytes", _raise_read_error)

    with pytest.raises(certs.CertsError, match="cannot read"):
        certs._require_parseable_ca_component(target, "sandbox")


# ---------------------------------------------------------------------------
# code_review round 1, WARN 5: `_issue_certificate` cleans up a truncated key
# or certificate at the real material path on a mid-issuance openssl
# failure, the same guarantee `create_ca` already gives its own material.
# ---------------------------------------------------------------------------


def test_issue_client_cleans_up_material_on_openssl_failure_mid_issuance(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    certs = _import_certs()
    paths = certs.CertPaths(instance=f"issue-fail-{uuid.uuid4().hex[:8]}", root=tmp_path)
    certs.create_ca(paths)
    failing_openssl = shutil.which("false")
    assert failing_openssl is not None, "the 'false' binary must be on PATH for this test"
    monkeypatch.setattr(certs, "OPENSSL_EXECUTABLE", failing_openssl)

    with pytest.raises(certs.CertsError, match="openssl"):
        certs.issue_client(paths)

    assert not paths.client_key.exists()
    assert not paths.client_cert.exists()


# ---------------------------------------------------------------------------
# code_review round 3, WARN C: rotating an existing, valid client certificate
# must never strand the developer without ANY client credential. The
# pre-round-3 implementation truncated `key_out` via
# `_prepare_output_file(allow_overwrite=True)` before the first `openssl`
# call, then unlinked both `key_out` and `cert_out` in the `except CertsError`
# handler, so a failing `openssl` during a rotation destroyed the previously
# valid key and certificate a running instance still trusted, with nothing
# to replace them. `_issue_certificate` now writes into a temporary
# directory on the SAME filesystem as the final destination and commits both
# files with `os.replace` only after every `openssl` call has succeeded, the
# same commit-only-on-success guarantee `create_ca` gives its own material,
# mirroring the temporary-directory pattern `issue_server` already uses.
# ---------------------------------------------------------------------------


def test_issue_client_rotation_does_not_strand_developer_without_credential(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    certs = _import_certs()
    paths = certs.CertPaths(instance=f"issue-rotate-fail-{uuid.uuid4().hex[:8]}", root=tmp_path)
    certs.create_ca(paths)
    certs.issue_client(paths)
    original_key = paths.client_key.read_text(encoding="ascii")
    original_cert = paths.client_cert.read_text(encoding="ascii")

    failing_openssl = shutil.which("false")
    assert failing_openssl is not None, "the 'false' binary must be on PATH for this test"
    monkeypatch.setattr(certs, "OPENSSL_EXECUTABLE", failing_openssl)

    with pytest.raises(certs.CertsError, match="openssl"):
        certs.issue_client(paths)

    assert paths.client_key.read_text(encoding="ascii") == original_key
    assert paths.client_cert.read_text(encoding="ascii") == original_cert


# ---------------------------------------------------------------------------
# E6-F1-S2-T1: rotate_client. AC-FUNC-001/AC-TEST-001 -- only cert.pem and
# key.pem ever change; the CA and the server material an already-running
# daemon depends on are untouched.
# ---------------------------------------------------------------------------


def test_rotate_client_changes_only_cert_and_key_files(tmp_path: Path) -> None:
    certs = _import_certs()
    paths = certs.CertPaths(instance=f"rotate-hash-{uuid.uuid4().hex[:8]}", root=tmp_path)
    certs.create_ca(paths)
    server = certs.issue_server(paths)
    certs.issue_client(paths)

    before = _hash_instance_directory(paths.instance_dir)
    certs.rotate_client(paths)
    after = _hash_instance_directory(paths.instance_dir)

    assert before.keys() == after.keys()
    changed = {name for name in before if before[name] != after[name]}
    assert changed == {certs.CLIENT_CERT_FILENAME, certs.CLIENT_KEY_FILENAME}

    # The CA the daemon's already-issued server certificate was signed
    # against is untouched: that server certificate (never persisted to
    # disk -- module docstring) still verifies against the unchanged
    # ca/ca.pem after the rotation.
    server_cert_path = tmp_path / "server-cert-for-verify.pem"
    server_cert_path.write_text(server.cert_pem, encoding="ascii")
    assert _verifies_against_ca(server_cert_path, paths.ca_cert)


# ---------------------------------------------------------------------------
# AC-FUNC-002/AC-TEST-002 -- the replacement is a real replacement: a fresh
# serial, a later notAfter, clientAuth, the fixed modes, and it verifies
# against the unchanged CA.
# ---------------------------------------------------------------------------


def test_rotate_client_produces_a_genuinely_different_certificate(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    certs = _import_certs()
    paths = certs.CertPaths(instance=f"rotate-diff-{uuid.uuid4().hex[:8]}", root=tmp_path)
    certs.create_ca(paths)
    certs.issue_client(paths)
    original_serial = _serial(paths.client_cert)
    original_not_after = certs.not_after(paths.client_cert)

    # A longer explicit lifetime for the rotation makes the later notAfter
    # deterministic rather than depending on the wall clock advancing
    # between two issuances -- openssl's own `-days` arithmetic has
    # one-second granularity, and two issuances of the same lifetime can
    # otherwise land in the same second and compare equal, not later.
    monkeypatch.setenv("CERT_CLIENT_DAYS", "91")
    certs.rotate_client(paths)

    assert _serial(paths.client_cert) != original_serial
    assert certs.not_after(paths.client_cert) > original_not_after
    assert _file_mode(paths.client_key) == 0o600
    assert _file_mode(paths.client_cert) == 0o644
    assert "TLS Web Client Authentication" in _openssl_text(paths.client_cert)
    assert _verifies_against_ca(paths.client_cert, paths.ca_cert)


# ---------------------------------------------------------------------------
# AC-FUNC-004/AC-TEST-003 -- atomicity: the final move (installing the
# rotated pair, `_commit_pair`) failing must leave the previous, matched
# pair in place, still verifying, with no temporary or backup file behind.
# ---------------------------------------------------------------------------


def test_rotate_client_final_move_failure_leaves_previous_pair_intact(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    certs = _import_certs()
    paths = certs.CertPaths(instance=f"rotate-move-fail-{uuid.uuid4().hex[:8]}", root=tmp_path)
    certs.create_ca(paths)
    certs.issue_client(paths)
    original_key = paths.client_key.read_bytes()
    original_cert = paths.client_cert.read_bytes()

    real_replace = certs.os.replace

    def _fail_on_cert_install(src: object, dst: object) -> None:
        # Only the install of the freshly issued certificate (source name
        # "issued-cert.pem", inside _issue_certificate's own temporary
        # directory) is made to fail here -- never the backup this failure
        # itself triggers inside `_commit_pair`'s `except` handler
        # (source name "cert.pem.rotate-previous"), or its own rollback
        # would recurse into this same simulated failure and never restore
        # the previous certificate at all.
        if Path(dst) == paths.client_cert and Path(src).name != certs.CLIENT_CERT_FILENAME + (
            certs._PAIR_BACKUP_SUFFIX
        ):
            raise OSError("simulated disk failure installing the rotated certificate")
        real_replace(src, dst)

    monkeypatch.setattr(certs.os, "replace", _fail_on_cert_install)

    with pytest.raises(certs.CertsError) as excinfo:
        certs.rotate_client(paths)

    message = str(excinfo.value)
    assert str(paths.client_key) in message
    assert str(paths.client_cert) in message
    assert paths.client_key.read_bytes() == original_key
    assert paths.client_cert.read_bytes() == original_cert
    assert _verifies_against_ca(paths.client_cert, paths.ca_cert)
    assert list(paths.instance_dir.glob(f"*{certs._PAIR_BACKUP_SUFFIX}")) == []


def test_commit_pair_failure_on_a_first_issuance_backs_up_nothing(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """The symmetric case to the rotation above: a *first* issuance has no
    previous key or certificate to back up, so `_commit_pair`'s own
    `backed_up_key`/`backed_up_cert` both stay `False` and its rollback is a
    no-op on this path -- distinct branch coverage from the rotation case,
    where both are `True`."""
    certs = _import_certs()
    paths = certs.CertPaths(instance=f"first-issue-fail-{uuid.uuid4().hex[:8]}", root=tmp_path)
    certs.create_ca(paths)

    def _always_fail(*_args: object, **_kwargs: object) -> None:
        raise OSError("simulated disk failure on a first issuance")

    monkeypatch.setattr(certs.os, "replace", _always_fail)

    with pytest.raises(certs.CertsError) as excinfo:
        certs.issue_client(paths)

    message = str(excinfo.value)
    assert str(paths.client_key) in message
    assert str(paths.client_cert) in message
    assert not paths.client_key.exists()
    assert not paths.client_cert.exists()


# ---------------------------------------------------------------------------
# AC-FUNC-005/AC-TEST-003 -- rotate_client refuses when no CA exists for the
# instance, names the skill invocation that creates one, and creates
# nothing itself.
# ---------------------------------------------------------------------------


def test_rotate_client_refuses_when_no_ca_exists_and_creates_nothing(tmp_path: Path) -> None:
    certs = _import_certs()
    instance = f"rotate-no-ca-{uuid.uuid4().hex[:8]}"
    paths = certs.CertPaths(instance=instance, root=tmp_path)

    with pytest.raises(certs.CertsError) as excinfo:
        certs.rotate_client(paths)

    message = str(excinfo.value)
    assert "no certificate authority" in message
    assert f"/devcontainer:certs INSTANCE={instance}" in message
    assert not paths.ca_key.exists()
    assert not paths.ca_cert.exists()
    assert not paths.client_key.exists()
    assert not paths.client_cert.exists()


# ---------------------------------------------------------------------------
# AC-FUNC-003/AC-TEST-004 -- rotation implies no publication work.
# ---------------------------------------------------------------------------


def test_rotate_client_returns_no_publication_work(tmp_path: Path) -> None:
    certs = _import_certs()
    paths = certs.CertPaths(instance=f"rotate-no-publish-{uuid.uuid4().hex[:8]}", root=tmp_path)
    certs.create_ca(paths)
    certs.issue_client(paths)
    before = certs.publication_set(paths.instance)

    result = certs.rotate_client(paths)

    assert result is None
    after = certs.publication_set(paths.instance)
    assert after == before
    observed = {(entry.parameter_path, entry.parameter_type) for entry in after}
    assert observed == {
        (f"/devcontainer/{paths.instance}/tls/server-key.pem", "SecureString"),
        (f"/devcontainer/{paths.instance}/tls/server-cert.pem", "SecureString"),
        (f"/devcontainer/{paths.instance}/tls/ca.pem", "String"),
    }


# ---------------------------------------------------------------------------
# code_review round 1, WARN 4: PARAMETER_ROOT and SECURE_STRING_TYPE are the
# same values catalog.py already defines, reused rather than redeclared.
# ---------------------------------------------------------------------------


def test_parameter_root_and_secure_string_type_are_reused_from_catalog() -> None:
    """Values must match catalog AND the source must reference catalog's
    attributes rather than redeclaring the same literals independently --
    equal values alone would not catch a second, independent definition
    that merely happens to agree with catalog's today."""
    certs = _import_certs()
    catalog = importlib.import_module("devcontainer_config.catalog")
    assert certs.PARAMETER_ROOT == catalog.PATH_ROOT
    assert certs.SECURE_STRING_TYPE == catalog.SECURE_STRING_TYPE

    source = _certs_module_path().read_text(encoding="utf-8")
    tree = ast.parse(source)
    reused_from_catalog = {
        target.id
        for node in ast.walk(tree)
        if isinstance(node, ast.Assign)
        for target in node.targets
        if isinstance(target, ast.Name)
        and target.id in {"PARAMETER_ROOT", "SECURE_STRING_TYPE"}
        and isinstance(node.value, ast.Attribute)
        and isinstance(node.value.value, ast.Name)
        and node.value.value.id == "catalog"
    }
    assert reused_from_catalog == {"PARAMETER_ROOT", "SECURE_STRING_TYPE"}


# ---------------------------------------------------------------------------
# E6-F1-S1-T2: expiry arithmetic and `make cert-status`. AC-FUNC-001,
# AC-FUNC-002, AC-TEST-001: `classify` and `days_remaining` take the
# reference time as a parameter, so the warning-window boundary is
# exercised with a fixed, injected clock rather than the real one -- every
# case below is exact and reproducible regardless of when the suite runs.
# ---------------------------------------------------------------------------

_REFERENCE_TIME = datetime.datetime(2026, 1, 1, tzinfo=datetime.UTC)


@pytest.mark.parametrize(
    "days_offset,expected_status",
    [
        (90, "ok"),
        (14, "RENEW"),
        (15, "ok"),
        (0, "RENEW"),
        (-1, "expired"),
    ],
)
def test_classify_boundary_from_both_sides(days_offset: int, expected_status: str) -> None:
    certs = _import_certs()
    cert_not_after = _REFERENCE_TIME + datetime.timedelta(days=days_offset)
    assert (
        certs.classify(cert_not_after, _REFERENCE_TIME, certs.CERT_WARN_DAYS_DEFAULT)
        == expected_status
    )


@pytest.mark.parametrize("days_offset", [90, -30, 0, 3650])
def test_days_remaining_returns_the_signed_day_delta(days_offset: int) -> None:
    certs = _import_certs()
    cert_not_after = _REFERENCE_TIME + datetime.timedelta(days=days_offset)
    assert certs.days_remaining(cert_not_after, _REFERENCE_TIME) == days_offset


def test_classify_boundary_moves_with_a_custom_warn_days_value() -> None:
    """The window is a parameter, never a constant baked into classify (AC-FUNC-007)."""
    certs = _import_certs()
    cert_not_after = _REFERENCE_TIME + datetime.timedelta(days=20)
    assert certs.classify(cert_not_after, _REFERENCE_TIME, 14) == "ok"
    assert certs.classify(cert_not_after, _REFERENCE_TIME, 20) == "RENEW"


# ---------------------------------------------------------------------------
# AC-FUNC-007: CERT_WARN_DAYS is read from the environment in exactly one
# place, defaults to 14, and rejects a non-integer or negative override
# before any row of the report is rendered.
# ---------------------------------------------------------------------------


def test_resolve_cert_warn_days_defaults_to_fourteen_when_unset(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    certs = _import_certs()
    monkeypatch.delenv("CERT_WARN_DAYS", raising=False)
    assert certs._resolve_cert_warn_days() == 14


def test_resolve_cert_warn_days_honors_override(monkeypatch: pytest.MonkeyPatch) -> None:
    certs = _import_certs()
    monkeypatch.setenv("CERT_WARN_DAYS", "30")
    assert certs._resolve_cert_warn_days() == 30


def test_resolve_cert_warn_days_accepts_zero(monkeypatch: pytest.MonkeyPatch) -> None:
    certs = _import_certs()
    monkeypatch.setenv("CERT_WARN_DAYS", "0")
    assert certs._resolve_cert_warn_days() == 0


@pytest.mark.parametrize("raw_value", ["not-a-number", "-1", "-30"])
def test_resolve_cert_warn_days_rejects_non_integer_or_negative_values(
    monkeypatch: pytest.MonkeyPatch, raw_value: str
) -> None:
    certs = _import_certs()
    monkeypatch.setenv("CERT_WARN_DAYS", raw_value)
    with pytest.raises(certs.CertsError, match="CERT_WARN_DAYS"):
        certs._resolve_cert_warn_days()


def test_cert_warn_days_env_var_is_read_in_exactly_one_place() -> None:
    """AC-FUNC-007: no call site anywhere in this module reads the environment a second time."""
    source = _certs_module_path().read_text(encoding="utf-8")
    assert source.count("os.environ.get(CERT_WARN_DAYS_ENV_VAR") == 1


def test_literal_fourteen_appears_exactly_once_in_the_module() -> None:
    """AC-FUNC-007: no call site hardcodes 14; only CERT_WARN_DAYS_DEFAULT's own literal does."""
    source = _certs_module_path().read_text(encoding="utf-8")
    tree = ast.parse(source)
    fourteen_constants = [
        node for node in ast.walk(tree) if isinstance(node, ast.Constant) and node.value == 14
    ]
    assert len(fourteen_constants) == 1


# ---------------------------------------------------------------------------
# not_after: real, on-disk certificates, parsed genuinely -- never re-reading
# the arguments this module passed to its own openssl calls (module
# docstring's own testing rule, extended to this new read path). Error path
# 1 of this task's Error Handling Contract: an unreadable or unparseable
# file raises naming the path, never silently classified as expired.
# ---------------------------------------------------------------------------


def test_not_after_matches_an_independent_openssl_parse(issued_material: _IssuedMaterial) -> None:
    certs = issued_material.certs
    result = subprocess.run(
        ["openssl", "x509", "-noout", "-enddate", "-in", str(issued_material.paths.ca_cert)],
        capture_output=True,
        text=True,
        check=True,
    )
    _, _, raw_date = result.stdout.strip().partition("=")
    expected = datetime.datetime.strptime(raw_date.strip(), "%b %d %H:%M:%S %Y %Z").replace(
        tzinfo=datetime.UTC
    )
    assert certs.not_after(issued_material.paths.ca_cert) == expected


def test_not_after_raises_naming_path_for_an_unreadable_file(tmp_path: Path) -> None:
    certs = _import_certs()
    target = tmp_path / "unreadable-cert.pem"
    target.write_bytes(b"-----BEGIN CERTIFICATE-----\nnot really a certificate\n")
    target.chmod(0o000)
    try:
        with pytest.raises(certs.CertsError) as excinfo:
            certs.not_after(target)
    finally:
        target.chmod(0o600)
    assert str(target) in str(excinfo.value)


def test_not_after_raises_naming_path_for_corrupt_content(tmp_path: Path) -> None:
    certs = _import_certs()
    target = tmp_path / "corrupt-cert.pem"
    target.write_bytes(b"not a certificate at all")
    with pytest.raises(certs.CertsError) as excinfo:
        certs.not_after(target)
    assert str(target) in str(excinfo.value)


def test_not_after_raises_when_openssl_succeeds_but_the_date_is_unparseable(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """A malicious or malformed `openssl` build that exits 0 with a nonsense
    `notAfter=` line is refused by name rather than crashing on a raw
    `ValueError` (Error Handling Contract)."""
    certs = _import_certs()
    target = tmp_path / "cert.pem"
    target.write_bytes(b"-----BEGIN CERTIFICATE-----\nplaceholder\n")

    class _FakeCompletedProcess:
        returncode = 0
        stdout = "notAfter=not a real date\n"
        stderr = ""

    monkeypatch.setattr(certs.subprocess, "run", lambda *args, **kwargs: _FakeCompletedProcess())

    with pytest.raises(certs.CertsError) as excinfo:
        certs.not_after(target)
    assert str(target) in str(excinfo.value)


# ---------------------------------------------------------------------------
# status_rows: instance discovery, the ca/client roles this module actually
# persists (module docstring's own note on why no server row exists), and
# the partial-material error path (Error Handling Contract, error path 3).
# ---------------------------------------------------------------------------


def test_status_rows_returns_nothing_for_a_root_that_does_not_exist(tmp_path: Path) -> None:
    certs = _import_certs()
    missing_root = tmp_path / "does-not-exist"
    rows = certs.status_rows(missing_root, _REFERENCE_TIME, certs.CERT_WARN_DAYS_DEFAULT)
    assert rows == ()


def test_status_rows_returns_nothing_for_an_empty_root(tmp_path: Path) -> None:
    certs = _import_certs()
    rows = certs.status_rows(tmp_path, _REFERENCE_TIME, certs.CERT_WARN_DAYS_DEFAULT)
    assert rows == ()


def test_status_rows_reports_ca_and_client_roles_for_an_instance(tmp_path: Path) -> None:
    certs = _import_certs()
    instance = f"status-{uuid.uuid4().hex[:8]}"
    paths = certs.CertPaths(instance=instance, root=tmp_path)
    certs.create_ca(paths)
    certs.issue_client(paths)

    rows = certs.status_rows(tmp_path, _REFERENCE_TIME, certs.CERT_WARN_DAYS_DEFAULT)

    assert {row.role for row in rows} == {"ca", "client"}
    assert all(row.instance == instance for row in rows)


def test_status_rows_reports_every_instance_under_root(tmp_path: Path) -> None:
    certs = _import_certs()
    instances = [f"status-multi-{uuid.uuid4().hex[:8]}" for _ in range(2)]
    for instance in instances:
        paths = certs.CertPaths(instance=instance, root=tmp_path)
        certs.create_ca(paths)
        certs.issue_client(paths)

    rows = certs.status_rows(tmp_path, _REFERENCE_TIME, certs.CERT_WARN_DAYS_DEFAULT)

    assert {row.instance for row in rows} == set(instances)


def test_status_rows_skips_an_instance_directory_with_no_material_yet(tmp_path: Path) -> None:
    """An instance directory that exists but holds neither role's certificate yet
    (for example, one left over from an interrupted `create_ca`) contributes
    no rows and raises nothing -- only a genuinely partial set (one role
    present, the other missing) is an error."""
    certs = _import_certs()
    instance = f"empty-{uuid.uuid4().hex[:8]}"
    (tmp_path / instance).mkdir()

    rows = certs.status_rows(tmp_path, _REFERENCE_TIME, certs.CERT_WARN_DAYS_DEFAULT)

    assert rows == ()


def test_status_rows_raises_naming_missing_ca_when_only_client_material_exists(
    tmp_path: Path,
) -> None:
    certs = _import_certs()
    instance = f"partial-{uuid.uuid4().hex[:8]}"
    instance_dir = tmp_path / instance
    instance_dir.mkdir()
    (instance_dir / "cert.pem").write_bytes(b"placeholder")

    with pytest.raises(certs.CertsError) as excinfo:
        certs.status_rows(tmp_path, _REFERENCE_TIME, certs.CERT_WARN_DAYS_DEFAULT)

    message = str(excinfo.value)
    assert instance in message
    assert "ca" in message


def test_status_rows_raises_naming_missing_client_when_only_ca_material_exists(
    tmp_path: Path,
) -> None:
    certs = _import_certs()
    instance = f"partial-{uuid.uuid4().hex[:8]}"
    paths = certs.CertPaths(instance=instance, root=tmp_path)
    certs.create_ca(paths)

    with pytest.raises(certs.CertsError) as excinfo:
        certs.status_rows(tmp_path, _REFERENCE_TIME, certs.CERT_WARN_DAYS_DEFAULT)

    message = str(excinfo.value)
    assert instance in message
    assert "client" in message


def test_role_cert_path_raises_naming_the_role_for_an_unrecognized_role(
    tmp_path: Path,
) -> None:
    """`_role_cert_path` resolves through an explicit mapping (code_review,
    E6-F1-S1-T2, WARN 4), so a role outside `_INSPECTABLE_ROLES` fails
    loudly naming itself instead of silently resolving to the CA
    certificate's path."""
    certs = _import_certs()
    paths = certs.CertPaths(instance=f"role-{uuid.uuid4().hex[:8]}", root=tmp_path)

    with pytest.raises(certs.CertsError) as excinfo:
        certs._role_cert_path(paths, "server")

    message = str(excinfo.value)
    assert "server" in message
    assert certs._role_cert_path(paths, certs.ROLE_CA) == paths.ca_cert


# ---------------------------------------------------------------------------
# render_report: the Section 4.1.2 column shape, the RENEW reissue
# invocation (AC-FUNC-005), and the empty-inventory edge case (AC-FUNC-006).
# Built from CertStatusRow values directly so the exact layout is pinned
# without needing real certificate files.
# ---------------------------------------------------------------------------


def test_render_report_matches_the_section_4_1_2_column_shape() -> None:
    certs = _import_certs()
    row = certs.CertStatusRow(
        instance="sandbox",
        role="client",
        not_after=datetime.datetime(2026, 11, 16, tzinfo=datetime.UTC),
        days=90,
        status="ok",
    )
    lines = certs.render_report([row]).splitlines()
    assert lines[0] == "INSTANCE   ROLE     EXPIRES       DAYS  STATUS"
    assert lines[1] == "sandbox    client   2026-11-16      90  ok"


def test_render_report_pads_large_day_counts_correctly() -> None:
    certs = _import_certs()
    row = certs.CertStatusRow(
        instance="sandbox",
        role="ca",
        not_after=datetime.datetime(2036, 8, 18, tzinfo=datetime.UTC),
        days=3650,
        status="ok",
    )
    lines = certs.render_report([row]).splitlines()
    assert lines[1] == "sandbox    ca       2036-08-18    3650  ok"


def test_render_report_renew_row_names_the_reissue_invocation() -> None:
    certs = _import_certs()
    row = certs.CertStatusRow(
        instance="personal",
        role="client",
        not_after=datetime.datetime(2026, 8, 29, tzinfo=datetime.UTC),
        days=11,
        status="RENEW",
    )
    lines = certs.render_report([row]).splitlines()
    assert lines[1] == (
        "personal   client   2026-08-29      11  RENEW   /devcontainer:certs INSTANCE=personal"
    )


def test_renew_invocation_template_is_public_and_matches_every_reissue_site(
    tmp_path: Path,
) -> None:
    """`RENEW_INVOCATION_TEMPLATE` (E6-F2-S1-T2's code_review round 1 fix) is
    public -- not `_RENEW_INVOCATION_TEMPLATE` -- because `devcontainer_config
    .transport` formats the identical `/devcontainer:certs INSTANCE={instance}`
    template in its own certificate-not-ready and SAN-mismatch remedies and
    must not carry a second, independently drifting copy of this module's own
    reissue invocation. Both real call sites -- the missing-CA remedy
    `_require_ca` raises through `issue_server`, and a `RENEW` status row
    `render_report` prints -- are exercised here and proven to emit the exact
    string `RENEW_INVOCATION_TEMPLATE.format(instance=...)` produces, not a
    hand-typed string that could independently agree with itself.
    """
    certs = _import_certs()

    assert certs.RENEW_INVOCATION_TEMPLATE == "/devcontainer:certs INSTANCE={instance}"
    assert not hasattr(certs, "_RENEW_INVOCATION_TEMPLATE")

    instance = f"no-ca-{uuid.uuid4().hex[:8]}"
    expected_invocation = certs.RENEW_INVOCATION_TEMPLATE.format(instance=instance)
    assert expected_invocation == f"/devcontainer:certs INSTANCE={instance}"

    paths = certs.CertPaths(instance=instance, root=tmp_path)
    with pytest.raises(certs.CertsError) as excinfo:
        certs.issue_server(paths)
    assert expected_invocation in str(excinfo.value)

    row = certs.CertStatusRow(
        instance=instance,
        role="client",
        not_after=datetime.datetime(2026, 8, 29, tzinfo=datetime.UTC),
        days=11,
        status=certs.STATUS_RENEW,
    )
    report_line = certs.render_report([row]).splitlines()[1]
    assert report_line.endswith(expected_invocation)


def test_render_report_with_no_rows_prints_header_and_setup_remote_line() -> None:
    certs = _import_certs()
    report = certs.render_report([])
    lines = report.splitlines()
    assert lines[0] == "INSTANCE   ROLE     EXPIRES       DAYS  STATUS"
    assert "/devcontainer:setup-remote" in report


# ---------------------------------------------------------------------------
# AC-FUNC-004, AC-TEST-002, AC-FINAL-010: the three-valued exit contract,
# exercised through the real `main(["status", ...])` CLI entry point against
# genuinely issued material. `_current_time` is the one seam `main`'s status
# command reads the real clock through; monkeypatching it forces `ok`,
# `RENEW` and `expired` outcomes deterministically instead of waiting real
# days for a certificate to age.
# ---------------------------------------------------------------------------


def test_main_status_exits_zero_when_every_certificate_is_ok(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    certs = _import_certs()
    instance = f"status-ok-{uuid.uuid4().hex[:8]}"
    paths = certs.CertPaths(instance=instance, root=tmp_path)
    certs.create_ca(paths)
    certs.issue_client(paths)
    client_not_after = certs.not_after(paths.client_cert)
    monkeypatch.setattr(
        certs, "_current_time", lambda: client_not_after - datetime.timedelta(days=30)
    )

    exit_code = certs.main(["status", "--root", str(tmp_path)])

    assert exit_code == 0
    captured = capsys.readouterr()
    assert instance in captured.out
    assert "RENEW" not in captured.out
    assert "expired" not in captured.out


def test_main_status_exits_zero_with_a_renew_row_present(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    certs = _import_certs()
    instance = f"status-renew-{uuid.uuid4().hex[:8]}"
    paths = certs.CertPaths(instance=instance, root=tmp_path)
    certs.create_ca(paths)
    certs.issue_client(paths)
    client_not_after = certs.not_after(paths.client_cert)
    monkeypatch.setattr(
        certs, "_current_time", lambda: client_not_after - datetime.timedelta(days=5)
    )

    exit_code = certs.main(["status", "--root", str(tmp_path)])

    assert exit_code == 0
    captured = capsys.readouterr()
    assert "RENEW" in captured.out
    assert f"/devcontainer:certs INSTANCE={instance}" in captured.out


def test_main_status_exits_one_when_a_certificate_has_expired(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    certs = _import_certs()
    instance = f"status-expired-{uuid.uuid4().hex[:8]}"
    paths = certs.CertPaths(instance=instance, root=tmp_path)
    certs.create_ca(paths)
    certs.issue_client(paths)
    client_not_after = certs.not_after(paths.client_cert)
    monkeypatch.setattr(
        certs, "_current_time", lambda: client_not_after + datetime.timedelta(days=1)
    )

    exit_code = certs.main(["status", "--root", str(tmp_path)])

    assert exit_code == 1
    captured = capsys.readouterr()
    assert "expired" in captured.out


def test_main_status_no_certificates_exits_zero_and_directs_to_setup_remote(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    certs = _import_certs()
    exit_code = certs.main(["status", "--root", str(tmp_path)])
    assert exit_code == 0
    captured = capsys.readouterr()
    assert "/devcontainer:setup-remote" in captured.out


def test_main_status_unreadable_certificate_exits_nonzero_naming_path(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    certs = _import_certs()
    instance = f"status-unreadable-{uuid.uuid4().hex[:8]}"
    paths = certs.CertPaths(instance=instance, root=tmp_path)
    certs.create_ca(paths)
    certs.issue_client(paths)
    paths.client_cert.chmod(0o000)

    try:
        exit_code = certs.main(["status", "--root", str(tmp_path)])
    finally:
        paths.client_cert.chmod(0o644)

    assert exit_code == 1
    captured = capsys.readouterr()
    assert "ERROR" in captured.err
    assert str(paths.client_cert) in captured.err


def test_main_status_respects_cert_warn_days_override(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    certs = _import_certs()
    instance = f"status-window-{uuid.uuid4().hex[:8]}"
    paths = certs.CertPaths(instance=instance, root=tmp_path)
    certs.create_ca(paths)
    certs.issue_client(paths)
    client_not_after = certs.not_after(paths.client_cert)
    monkeypatch.setattr(
        certs, "_current_time", lambda: client_not_after - datetime.timedelta(days=20)
    )
    monkeypatch.delenv("CERT_WARN_DAYS", raising=False)

    exit_code = certs.main(["status", "--root", str(tmp_path)])
    assert exit_code == 0
    assert "RENEW" not in capsys.readouterr().out

    monkeypatch.setenv("CERT_WARN_DAYS", "20")
    exit_code = certs.main(["status", "--root", str(tmp_path)])
    assert exit_code == 0
    assert "RENEW" in capsys.readouterr().out
