"""Turn validated answers into the three private config files (spec Section 5.2).

Rendering rewrites the committed `.example` files rather than generating
content from scratch. The examples carry the explanatory comments and the
canonical variable set, so templating from them keeps one source of truth: a
variable added to an example reaches a rendered file with no change here,
and nobody has to keep this module and three example files in step by hand.
The consequence is that `set_export` fails when the variable it was asked to
set has no line in the example, rather than appending one, because an
appended line would look correct while setting the value in the wrong place
or not at all.

`render_all` produces every file's content in memory and `write_all` commits
them together, so an interview aborted partway through the answers leaves no
file written and the working tree unchanged (AC-4.2, spec Section 4.2.2):
nothing partial is ever on disk.
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Any

from . import answers as answers_module
from . import repo

# Everything above this marker in shell.env.example explains how to copy the
# example by hand. A rendered file is not a copy anyone typed, so the
# instructions above the marker are replaced by RENDERED_HEADER instead, and
# everything from the marker onward is preserved unchanged.
SHELL_ENV_HEADER_MARKER = "########################"

RENDERED_HEADER = """\
# shell.env, generated by the devcontainer skills from your answers.
#
# Sourced by every shell in the container (.bashrc and .zshenv), and published
# to Parameter Store by `make push-secrets` for remote builds.
#
# Gitignored, and blocked from being committed by the pre-commit hook.
# Carries per-developer identity and configuration only, never a credential:
# every credential lives in the secret catalog, reached through `devsecret
# set`, not in this file.
#
# Re-run /devcontainer:setup-local (or /devcontainer:setup-remote for a
# remote backend) to change any of it, or edit in place: the file is read
# as-is, nothing regenerates it behind your back.
# What each value does: docs/environment-files.md
"""

# The optional remote-docker block (spec Section 5.2): populated and
# uncommented on a remote payload, left commented out exactly as the example
# ships it on a local payload.
_REMOTE_VARIABLES: tuple[str, ...] = (
    "REMOTE_INSTANCE_ID",
    "REMOTE_SSH_KEY_PATH",
    "REMOTE_AWS_REGION",
    "REMOTE_AWS_PROFILE",
)

# The proxy variables that mirror HOST_PROXY_URL once a host proxy is in use;
# left empty (their example default) when host_proxy is false.
_PROXY_MIRROR_VARIABLES: tuple[str, ...] = (
    "HOST_PROXY_URL",
    "HTTP_PROXY",
    "HTTPS_PROXY",
    "http_proxy",
    "https_proxy",
)

# The six sub-fields written under each profile in
# .devcontainer/aws-profile-map.json (spec Section 5.1's seventh field,
# `name`, is consumed as the map key instead, so it is excluded here).
# Derived from `answers_module.AWS_PROFILE_SUB_FIELDS` rather than restated
# as its own tuple literal, so a sub-field added there reaches a rendered
# profile with no change here.
_AWS_PROFILE_MAP_SUB_FIELDS: tuple[str, ...] = tuple(
    field for field in answers_module.AWS_PROFILE_SUB_FIELDS if field != "name"
)

# One of the two literals `answers_module.BACKENDS` declares; the module
# exports the set itself but not either member by name, so the one this
# file branches on is named once, here, rather than repeated as a bare
# string at the branch site below. Kept in step with `answers_module.BACKENDS`
# by `tests/test_render.py`, which asserts membership directly.
_BACKEND_REMOTE = "remote"


class RenderError(RuntimeError):
    """Raised when an example is not shaped the way rendering needs, or when
    `write_all` is asked to write over files it was not told to replace.
    """


def shell_quote(value: str) -> str:
    """A single-quoted shell literal, safe for any content.

    A single quote inside single quotes has to close the quoting, emit an
    escaped quote, and reopen it (`'\\''`), which is what the replacement
    below does. Names like O'Brien reach this path.
    """
    escaped = value.replace("'", "'\\''")
    return f"'{escaped}'"


def home_relative(path: str, home: Path) -> str:
    """A path expressed against `${HOME}` when it is under it, quoted for shell.

    The example writes `REMOTE_SSH_KEY_PATH` this way. Keeping the form means
    the rendered file stays readable and portable between accounts. A path
    outside `home` falls back to a single-quoted literal instead, since there
    is nothing to make it relative to.
    """
    expanded = Path(path).expanduser()
    try:
        relative = expanded.relative_to(home)
    except ValueError:
        return shell_quote(str(expanded))
    return f'"${{HOME}}/{relative}"'


def set_export(text: str, variable: str, quoted_value: str) -> str:
    """Set `export VARIABLE=...` to an already-quoted value.

    Uncomments the line when the example ships it commented out, which is
    how the optional remote block is populated. Raises `RenderError` naming
    `variable` when no matching line exists, rather than appending one,
    because an appended line would look correct while setting the value in
    the wrong place or not at all.
    """
    pattern = re.compile(
        rf"^(?P<indent>[ \t]*)(?:#[ \t]*)?export[ \t]+{re.escape(variable)}=.*$",
        re.MULTILINE,
    )
    if not pattern.search(text):
        raise RenderError(
            f"no 'export {variable}=' line in {repo.example_for(repo.SHELL_ENV)} to set"
        )
    return pattern.sub(
        lambda match: f"{match.group('indent')}export {variable}={quoted_value}",
        text,
        count=1,
    )


def comment_export(text: str, variable: str) -> str:
    """Leave `export VARIABLE=` commented out, exactly as the example ships it.

    Raises `RenderError` naming `variable` when no matching line exists, for
    the same reason `set_export` does: a silently accepted no-op would hide a
    typo in the variable name.
    """
    pattern = re.compile(
        rf"^(?P<indent>[ \t]*)(?P<hash>#[ \t]*)?(?P<body>export[ \t]+{re.escape(variable)}=.*)$",
        re.MULTILINE,
    )
    if not pattern.search(text):
        raise RenderError(
            f"no 'export {variable}=' line in {repo.example_for(repo.SHELL_ENV)} to comment out"
        )

    def _comment(match: re.Match[str]) -> str:
        hash_prefix = match.group("hash") or "# "
        return match.group("indent") + hash_prefix + match.group("body")

    return pattern.sub(_comment, text, count=1)


def replace_header(text: str) -> str:
    """Swap the example's copy instructions for a header describing the real file.

    Everything from `SHELL_ENV_HEADER_MARKER` onward is preserved unchanged;
    only the copy-instruction preamble above it is replaced.
    """
    index = text.find(SHELL_ENV_HEADER_MARKER)
    if index == -1:
        raise RenderError(
            f"{repo.example_for(repo.SHELL_ENV)} has no {SHELL_ENV_HEADER_MARKER!r} "
            "section marker, so the copy-instruction header cannot be replaced"
        )
    return RENDERED_HEADER + text[index:]


def render_shell_env(validated: dict[str, Any], example: str, root: Path, home: Path) -> str:
    """`shell.env` content for the given, already-validated answers."""
    text = replace_header(example)

    text = set_export(text, "DEVELOPER_NAME", shell_quote(validated["developer_name"]))
    text = set_export(text, "GIT_USER", shell_quote(validated["git_user"]))
    text = set_export(text, "GIT_USER_EMAIL", shell_quote(validated["git_user_email"]))
    text = set_export(text, "GIT_PROVIDER_URL", shell_quote(validated["git_provider_url"]))
    text = set_export(text, "DEFAULT_GIT_BRANCH", shell_quote(validated["default_git_branch"]))
    aws_config_enabled = "true" if validated["aws_config_enabled"] else "false"
    text = set_export(text, "AWS_CONFIG_ENABLED", shell_quote(aws_config_enabled))
    text = set_export(
        text, "BASH_ENV", shell_quote(f"{repo.container_workspace(root)}/{repo.SHELL_ENV}")
    )

    proxy_on = bool(validated["host_proxy"])
    # host_proxy_url is Requiredness.WHEN_PROXY (answers_module.FIELDS), so
    # ensure_valid guarantees the key is present whenever proxy_on is true;
    # indexing directly means a validation-contract regression raises here
    # instead of silently rendering an empty proxy URL.
    proxy_url = validated["host_proxy_url"] if proxy_on else ""
    text = set_export(text, "HOST_PROXY", shell_quote("true" if proxy_on else "false"))
    for variable in _PROXY_MIRROR_VARIABLES:
        text = set_export(text, variable, shell_quote(proxy_url))

    if validated["backend"] == _BACKEND_REMOTE:
        text = set_export(text, "REMOTE_INSTANCE_ID", shell_quote(validated["remote_instance_id"]))
        text = set_export(
            text, "REMOTE_SSH_KEY_PATH", home_relative(validated["remote_ssh_key_path"], home)
        )
        text = set_export(text, "REMOTE_AWS_REGION", shell_quote(validated["remote_aws_region"]))
        text = set_export(text, "REMOTE_AWS_PROFILE", shell_quote(validated["remote_aws_profile"]))
    else:
        for variable in _REMOTE_VARIABLES:
            text = comment_export(text, variable)

    return text


def render_devcontainer_env_json(validated: dict[str, Any], example: str) -> str:
    """`devcontainer-environment-variables.json` content for the given answers."""
    try:
        document = json.loads(example)
    except json.JSONDecodeError as exc:
        raise RenderError(
            f"{repo.example_for(repo.DEVCONTAINER_ENV_JSON)} does not parse: {exc}"
        ) from exc

    if "containerEnv" not in document:
        raise RenderError(
            f"{repo.example_for(repo.DEVCONTAINER_ENV_JSON)} has no 'containerEnv' object"
        )

    document["template_name"] = validated["template_name"]
    # The example documents template_path as optional. Nothing in this repo
    # reads it, and a placeholder left behind would fail verification, so it
    # is dropped rather than guessed.
    document.pop("template_path", None)

    proxy_on = bool(validated["host_proxy"])
    document["containerEnv"].update(
        {
            "DEVELOPER_NAME": validated["developer_name"],
            "GIT_USER": validated["git_user"],
            "GIT_USER_EMAIL": validated["git_user_email"],
            "GIT_PROVIDER_URL": validated["git_provider_url"],
            "DEFAULT_GIT_BRANCH": validated["default_git_branch"],
            "AWS_CONFIG_ENABLED": "true" if validated["aws_config_enabled"] else "false",
            "HOST_PROXY": "true" if proxy_on else "false",
            # See the matching comment in render_shell_env: indexing directly
            # means a validation-contract regression raises instead of
            # silently rendering an empty proxy URL.
            "HOST_PROXY_URL": validated["host_proxy_url"] if proxy_on else "",
        }
    )
    return json.dumps(document, indent=2) + "\n"


def render_aws_profile_map(validated: dict[str, Any]) -> str:
    """`.devcontainer/aws-profile-map.json` content for the given answers.

    An empty object when AWS profiles are switched off: the file still has
    to exist and parse, and the container skips the step that reads it
    (spec Section 5.2).
    """
    if not validated["aws_config_enabled"]:
        return "{}\n"

    document = {
        profile["name"]: {
            sub_field: profile[sub_field] for sub_field in _AWS_PROFILE_MAP_SUB_FIELDS
        }
        for profile in validated["aws_profiles"]
    }
    return json.dumps(document, indent=2) + "\n"


def render_all(raw_answers: dict[str, Any], root: Path, home: Path) -> dict[str, str]:
    """Every private file's content, keyed by its `repo.PRIVATE_FILES` name.

    Validates `raw_answers` first (AC-FUNC-002), so an invalid payload
    raises before any file content is produced, and checks every example is
    present (AC-FUNC-003) before rendering any of them, so a render either
    produces all three files' content or none of it.
    """
    validated = answers_module.ensure_valid(raw_answers)

    absent = repo.missing_examples(root)
    if absent:
        raise RenderError(
            "these example files are missing, so nothing can be rendered from "
            "them: " + ", ".join(absent)
        )

    def example_text(relative: str) -> str:
        return (root / repo.example_for(relative)).read_text(encoding="utf-8")

    return {
        repo.SHELL_ENV: render_shell_env(validated, example_text(repo.SHELL_ENV), root, home),
        repo.DEVCONTAINER_ENV_JSON: render_devcontainer_env_json(
            validated, example_text(repo.DEVCONTAINER_ENV_JSON)
        ),
        repo.AWS_PROFILE_MAP: render_aws_profile_map(validated),
    }


def write_all(rendered: dict[str, str], root: Path, overwrite: bool) -> list[str]:
    """Write rendered content to `root`, returning the sorted paths written.

    Refuses to write any file when one of the targets already exists and
    `overwrite` is false, because these files hold identity, and
    historically credentials, that someone may already have edited by hand;
    silently replacing a hand-edited file would discard that edit with no
    warning. The refusal names every existing path so the caller knows
    exactly what stood in the way, and leaves every file on disk untouched.
    """
    existing = sorted(relative for relative in rendered if (root / relative).exists())
    if existing and not overwrite:
        raise RenderError(
            "these files already exist and would be overwritten: "
            + ", ".join(existing)
            + ". Pass --overwrite to replace them."
        )

    written: list[str] = []
    for relative, content in rendered.items():
        destination = root / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        # Created with O_CREAT at mode 0600 directly, rather than
        # Path.write_text followed by chmod: write_text opens with O_CREAT at
        # 0666 & ~umask, so a freshly-created file would exist at a wider
        # mode (e.g. 0644) carrying its full contents for the instant before
        # a later chmod narrows it (CWE-732/CWE-279). os.open's mode
        # argument only governs file creation, so the explicit chmod below
        # still runs, to narrow a pre-existing wider file on the overwrite
        # path.
        descriptor = os.open(destination, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(content)
        # Identity and, historically, credentials: readable by the owner only.
        destination.chmod(0o600)
        written.append(relative)
    return sorted(written)
