
set -g default-shell /usr/bin/zsh

set -g mouse on

set -g history-limit 100000

set -g status on
set -g status-position bottom
set -g status-interval 5

set -g status-left " #{S:#{?#{==:#{session_name},#{client_session}},#[reverse] #{session_name} #[noreverse], #{session_name} }}#[default]| "
set -g status-left-length 60
set -g status-right " %H:%M "

set -g window-status-format " #I #W "
set -g window-status-current-format " #I #W "
set -g window-status-current-style bold,reverse
set -g window-status-separator ""

set -g renumber-windows on
